### ISSUE TITLE
Migrate themes to material components

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#119]
Review and improve our themes definitions.
Our base themes should be based on `Theme.MaterialComponents` instead of `Theme.AppCompat`.
- [x] Could we change theme without having to restart our app?
- [x] Auto dark theme support, see DayNight.
- [ ] Keep removing custom themes attributes where appropriates.
- [x] Theme popup menu background properly including shadow and corners.
- [x] Theme reader mode loading dialog.

See:
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme
https://medium.com/androiddevelopers/android-styling-common-theme-attributes-8f7c50c9eaba

Dark theme:
https://material.io/develop/android/theming/dark
https://developer.android.com/guide/topics/ui/look-and-feel/darktheme
https://material.io/design/color/dark-theme.html#usage

Standard theme attributes:
https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/res/res/values/attrs.xml#L24
https://stackoverflow.com/a/41289647/3969362

Most interesting articles and sample about AndroidX material themes:
https://medium.com/over-engineering/setting-up-a-material-components-theme-for-android-fbf7774da739
https://github.com/ricknout/android-mdc-theming
⚠️ See catalog app far examples: https://github.com/material-components/material-components-android
https://material.io/blog/android-material-theme-color
⚠️ https://material.io/blog/migrate-android-material-components

**Comment by jamal2362** [comment]
Is this helping you ?

https://github.com/jamal2362/Styx/commit/252e53bfc7a1420465fc3b25cc22abfebf983d8c
