### ISSUE TITLE
Remove prompt to use external apps 

### ISSUE THREAD

**Issue by christubuntu** [Slion/Fulguris#138]
Add, in the settings, an option to allow/deny opening in external apps, thus removing that constant prompt to do it every time.

**Comment by Slion** [comment]
You should only get that prompt once per site/app right?
I'm with you though external app manager should be improved at some point.
Would be nice to be able to delete single entries for instance.

**Comment by doxioxi** [comment]
> Would be nice to be able to delete single entries for instance.

I would love to see this feature.

**Comment by Slion** [comment]
It's currently being worked on as part of the domain settings.
