### ISSUE TITLE
Migrate to Storage Access Framework

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#141]
Direct access to file system was further restricted from Android 10.
That was notably breaking our bookmark backup feature, see #140.
We worked around those issues by using a [legacy mode][1].
However we will need to migrate to [Storage Access Framework][2] if we are to target SDKs above 29/Android 10.

[1]: https://developer.android.com/training/data-storage/use-cases#opt-out-scoped-storage
[2]: https://developer.android.com/guide/topics/providers/document-provider

See: https://stackoverflow.com/a/58379655/3969362

**Comment by jamal2362** [comment]
👍

**Comment by jamal2362** [comment]
I received a message in the Play Console, maybe this is relevant.

The app must use the Storage Access Framework or Media Store API to download files and create backups by May 5, or the app cannot release for Android 11 or later, and by November the app will be removed from the Play Store.

**Comment by Slion** [comment]
Using Storage Access Framework may not be needed. We should just look at our use cases and address them one by one:
* Import bookmarks
* Export bookmarks
* Write exception logs

For bookmark import  take a look at:
https://developer.android.com/training/data-storage/use-cases#open-document

For bookmark export and error logs:
https://developer.android.com/training/data-storage/use-cases#write-files-secondary-storage-volumes

**Comment by Slion** [comment]
Here is the [android.com article](https://developer.android.com/about/versions/11/privacy/storage) where they talk about enforcing scoped storage.
