### ISSUE TITLE
Save web page as PDF

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#158]
Dwight Boyd asked us to support saving web pages as PDF.

See: 
https://stackoverflow.com/questions/26841501/save-pdf-from-webview-on-android/43247149
http://www.annalytics.co.uk/android/pdf/2017/04/06/Save-PDF-From-An-Android-WebView/

I guess this should be implemented after our configurable menu to avoid menu clutter?

**Comment by jamal2362** [comment]
Wow! That sounds good.
I did not know that such a thing is possible.

**Comment by Slion** [comment]
It's basically a print to PDF I think. So here again I guess we should implement print functionality and have a PDF option.

**Comment by jamal2362** [comment]
That's great!

**Comment by jamal2362** [comment]
Here can you grab the Code.
This works fine 👍 

https://github.com/jamal2362/Styx/commit/0ddb019f6c7464f44481a8b81c34e7f298eda1b8

**Comment by jamal2362** [comment]
![Screenshot_20210220-215701](https://user-images.githubusercontent.com/15986930/108608370-c9b91180-73c6-11eb-82b6-49c7651638bf.jpg)

![Screenshot_20210220-215720](https://user-images.githubusercontent.com/15986930/108608351-bc9c2280-73c6-11eb-8c16-20a95363b53d.jpg)

**Comment by Slion** [comment]
Looks great, however that sounds like a pain to bring back in the Fulguris fork. I don't think I can just do a pull from your repo.
