### ISSUE TITLE
Pop-up menu shadow on longer click does not fit.

### ISSUE THREAD

**Issue by jamal2362** [Slion/Fulguris#160]
Pop-up menu shadow on longer click does not fit.

I have tried to fix the bug myself, but I can't find it.
Very unusual bug. 😄

You can see the circle in the Pictures:
![Screenshot_20210219-110405](https://user-images.githubusercontent.com/15986930/108489845-574f1100-72a2-11eb-82f0-636dce780a14.jpg)

Here an example from the URL Radio as it should be otherwise:
![Screenshot_20210219-110750](https://user-images.githubusercontent.com/15986930/108490264-d93f3a00-72a2-11eb-8cbc-7895ba5698ac.jpg)

**Comment by creativetrendsapps** [comment]
🙄

**Comment by jamal2362** [comment]
😂

**Comment by jamal2362** [comment]
https://github.com/jamal2362/Styx/commit/35962b40b640c98b242d0c1244ea00df3b156744
