### ISSUE TITLE
Close button for incognito mode

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#163]
Add main menu close button for incognito mode.

**Comment by Slion** [comment]
Duplicate #93

**Comment by jamal2362** [comment]
I finished it the other day.

A pull request from me is not possible, but it is quickly inside Fulguris with a few copy/paste.

Here is the commit:
https://github.com/jamal2362/Styx/commit/8975f8dd2c163699018528f781ef3344da8b060b

And a screen:
![Screenshot_20210223-192310](https://user-images.githubusercontent.com/15986930/108889402-a1225900-760c-11eb-975b-46c920afb788.jpg)

**Comment by Slion** [comment]
Was fixed as part of:
https://github.com/Slion/Fulguris/commit/12a2e205d0b4e6b2253320c0c15fa858c9d808a1
