### ISSUE TITLE
Fulguris flagged for trojans 

### ISSUE THREAD

**Issue by jrbdog** [Slion/Fulguris#176]
# Description
Lookout Mobile Security is flagging Fulguris  as having trojans. It complains about the app being able to open a network tunnel to a 3rd party server.
Fulguris version: 1.4.7
Lookout version: 10.36.3-877b68b

# Environment
 - Device: OnePlus 8
 - OS: Oxygen OS (Android 11)
 - Version: 11.0.1.2.IN55CB

# Screenshots
![Screenshot_20210313-155547.jpg](https://user-images.githubusercontent.com/35860079/111052086-31d2a480-8415-11eb-8ddd-8bcf71baf724.jpg)

**Comment by Slion** [comment]
Maybe because of the orbot proxy functionality. I'm afraid there is not much I can do about it. Just don't use orbot I guess if you don't trust it.

**Comment by jrbdog** [comment]
I thought that too, but wouldn't the tunneling be done by Orbot, not Fulguris?

**Comment by Slion** [comment]
> I thought that too, but wouldn't the tunneling be done by Orbot, not Fulguris?

Well it is definitly triggered by Fulguris so I guess that's enough to be flagged.
