### ISSUE TITLE
Bitwarden autofill not working

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#177]
Looking in Bitwarden C# source code it looks like the are checking that WebDomain property. I guess we should debug what's going on in Bitwarden to see if we can fix this. See Parser.SetPackageAndDomain in Bitwarden code.

See:
https://community.bitwarden.com/t/there-are-no-items-in-your-vault-for-com-android-chrome/7277
https://developer.android.com/reference/android/service/autofill/AutofillService#web-security
https://developer.android.com/guide/topics/text/autofill-optimize#force
https://github.com/bitwarden/mobile/issues/489

**Comment by jamal2362** [comment]
I think you must make an Pull-Request with your Package name.

Look here https://github.com/bitwarden/mobile/pull/1281

**Comment by Slion** [comment]
I could test it and it seems to be working just fine. Hopefully it should be merged and released soon enough.
https://github.com/bitwarden/mobile/pull/1333

**Comment by jamal2362** [comment]
Great! :)

**Comment by panbroggi** [comment]
HI. I tried fulguris both from F-droid and Play Store and came across this issue. I use the F-Droid.version of Bitwarden, can this be the issue?

**Comment by panbroggi** [comment]
Sorry, to be more explicit: it.looks like Bitwarden autofill is no longer working.

**Comment by Slion** [comment]
Sorry about that, it could be a while until I get a chance to look into it again.

**Comment by Slion** [comment]
I just tried with the non-f-droid variant of Bitwarden on Windows 11 and it seems to be working just fine.
@panbroggi I'm going to close this issue again as Bitwarden in general seems to be working fine.
If you are still having problems please open a new ticket and provide as much detail as possible about your speciric use case. Device, OS, WebView, app variant and so on…
