### ISSUE TITLE
Continuous localization

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#185]
Consider hosting and using:
https://weblate.org

**Comment by jamal2362** [comment]
When it is ready, I will do the German translation.

**Comment by Slion** [comment]
I've setup a crowdin project too. That weblate stuff is just too much work for now. Crongrats on rolling out your crowdin project.

**Comment by jamal2362** [comment]
This is also the reason why I went to Crowdin.

Weblate was too complicated for me.
Plus they have more criteria to host a project there.

**Comment by Slion** [comment]
[CrowdIn project](https://crowdin.com/project/fulguris-web-browser) has been setup.
Here is a useful link about [localization on Android.](https://developer.android.com/guide/topics/resources/localization).
