### ISSUE TITLE
Some times browsing get lag when using this app so plaese fix it and make app super faster for browsing 

### ISSUE THREAD

**Issue by Rajagithub07** [Slion/Fulguris#216]
# Description

# Environment
 - Device: [e.g. F(x)tec Pro¹ - QX1000]
 - OS: [e.g. Android 9]
 - Version: [e.g. 1.1.3]

# To reproduce
Steps to reproduce the behaviour:

# Expected behaviour

# Screenshots

# Additional context

**Comment by Uranite** [comment]
what in the bug report

**Comment by Rajagithub07** [comment]
I put black theme but when I open the app it displayed white screen for few seconds and then it shows dark screen
In desktop mode it gets lag for few seconds when I move to other app and then comes to Fulguris app
During browsing sometimes bit stuck/lags happened so make the app lite and faster for browsing
Please Increase  the width to 8k screen  as it increase the amazing user experience

**Comment by Rajagithub07** [comment]
Dear sir,
I put black theme but when I open the app it displayed white screen for few
seconds and then it shows dark screen
In desktop mode it gets lag for few seconds when I move to other app and
then comes to Fulguris app
During browsing sometimes bit stuck/lags happened so make the app lite and
faster for browsing.
Feature request;
Please Increase  the width to 8k screen  as it increase the amazing user
experience &many devices will compatible with 8k screen also
So I request you to please fix the bug  faster and provide the features
quickly.

**Comment by Slion** [comment]
Please stay on point, one topic per issue. As discussed by e-mail the lags you are observing are very likely due to the fact to you are using a very wide desktop viewport.

**Comment by Rajagithub07** [comment]
Dear sir,
               Thank you very much  for  your reply in github and being
patience for my mails & github issues.At present the app is so faster &
there is no  issues  except said more unlock zoom option.So I request you
to kindly unlock more zoom level if you have available resources.
Thanking🙏you sir 😀

**Comment by Rajagithub07** [comment]
Sir app is great can you please provide developer features mode,lite mode,
simplified view of webpages,force enabled zoom in and out,unlock more width
and height option,super fast loading of pages etc 🙏🙏
