### ISSUE TITLE
Remove content control Internal List filters file

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#222]
Do we still need our content control Internal List filters?
My feeling is that we should remove it to avoid having to maintain such a filters list which is outside the scope of this project.
Is there any reason why this was kept in place? Am I missing something?

**Comment by Helium314** [comment]
I only commented the internal list to make it easy to enable it again, as I thought it might be uesful to provide some small initial bloklist. But this would only make sense if blocking was enabled by default.

So internal list handling definitely can be removed, which I will do once I find some time.

**Comment by Slion** [comment]
I was just opening this issue because that Internal List is still showing in the settings. I have no idea if it still actually used.

I don't see any advantage in providing a built-in filters file. I mean it's a web browser it needs to be online to do anything, so while you are online you may as well just download the default filters if you don't have them yet. Also we support local filters file so that can be used to.

As for the timing of the fix, take all the time you need, there is never any urgency in anything I push your way. This is not a job it's supposed to be fun :)

**Comment by Helium314** [comment]
Oh, it should definitely not show... I guess you upgraded from some older version with the content blocker?
The internal list is removed from the default preferences, see
https://github.com/Slion/Fulguris/blob/a1546e7c9f42768ca7a0808bfc8ea53972a1a5a3/app/src/main/java/jp/hazuki/yuzubrowser/adblock/repository/abp/AbpDao.kt#L81
But if you already used/enabled the blocker before, the change in defaults does not affect you and the internal list keeps showing.

Currently there is no way to remove this list besides directly editing the ad block preferences xml file.
Not sure if this needs to be fixed, as it does not affect new users.
But anyway, I will remove the code for the internal list.

**Comment by Slion** [comment]
So looks like we are done with this then.
