### ISSUE TITLE
Issue with text boxes in web pages

### ISSUE THREAD

**Issue by Zero3K** [Slion/Fulguris#235]
# Description
When moving the text caret in any text box in a web page, a faded one shows up one or more times in the same text box.

# Environment
 - Device: Lenovo TB-X505F
 - OS: Android 10
 - Version: 1.6.12

# To reproduce
Steps to reproduce the behaviour:
1. Go to https://cs.hofstra.edu/javascript/chapter3.html
2. Try typing stuff into one of the text boxes on that page.
3. Move the text caret around in that text box.

# Expected behaviour
There should be no faded text caret(s) showing in the text box.

**Comment by Slion** [comment]
Can't reproduce. Did you try updating your [WebView] to see if that helps?

[WebView]: https://github.com/Slion/Fulguris/wiki/WebView

**Comment by Zero3K** [comment]
Its no longer happening for me either.

**Comment by Slion** [comment]
Was likely an issue with your WebView which has since been patch.
