### ISSUE TITLE
Add SSL Cert SHA-256 / SHA-1 Info?

### ISSUE THREAD

**Issue by Kita2345** [Slion/Fulguris#238]
Hi,

I am authenticating my connections to various sites by confirming their SSL certificate fingerprint using https://www.grc.com/fingerprints.htm.

GRC manually checks the SSL fingerprint of a given website, and returns its authenticated SHA-256 and SHA-1 hash value. However, when I check the SSL certificate in Fulguris neither values (SHA-256 or SHA-1) are listed, so a quick comparison of the SSL certificate against the authenticated information from GRC cannot be done.

Is it possible to add the SHA-256 and SHA-1 to the SSL certification tab info?

**Comment by jamal2362** [comment]
@Kita2345
Do you mean something like in this picture?
This has been implemented in the Styx browser for a long time.

![Screenshot_20210804-191833](https://user-images.githubusercontent.com/15986930/128225632-3d39b253-845b-4a1e-a54c-3600c19c225b.jpg)


@Slion here is the commit.
I hope this helps.
https://github.com/jamal2362/Styx/commit/a3950dad0ebd11d336e18f9d998649d9e4c55132

**Comment by jamal2362** [comment]
I have improved it a little bit.

More information is displayed and I added the algorithm OID.

And the dialog is scrollable now, should be better for devices that have a small resolution.

If now a fingerprint (SHA256) is still necessary I doubt.

![Screenshot_20210804-212957](https://user-images.githubusercontent.com/15986930/128243628-8f416b06-8bc6-4db0-abab-44ea6e79b9ba.jpg)

**Comment by Slion** [comment]
Looks like this was fixed when Styx features where contributed back. Please reopen if something is still missing.
