### ISSUE TITLE
Search on page: Improvements

### ISSUE THREAD

**Issue by zwim** [Slion/Fulguris#244]
**Is your feature request related to a problem? Please describe.**
Last input of seach in page cannot be reused. If you are searching similar strings you have to enter them again amd again. (e.g. color coulor) 

**Describe the solution you'd like**
First and easiest solution would be to fill the input field with the last search.

Additionally it would be cool if a regex pattern could be entered in the find input.

**Comment by Slion** [comment]
Duplicate of https://github.com/Slion/Fulguris/issues/172
