### ISSUE TITLE
[solved] Problem with web site certificates and adblocker

### ISSUE THREAD

**Issue by zwmn-beep** [Slion/Fulguris#245]
# Description
Problem with certificates of web sites, when an adblocker (AdAway) is activated.
**->The solution is to install a certificate on the adaway webserver or use ip-adress 0.0.0.0**

# Environment
 - Device: Pixel 4a
 - OS:  Android 11
 - Version:  1.7.7

# To reproduce
1. Open some web sites
2. See error -> screenshot

# Screenshots
![Screenshot_20210812-144852_Fulguris](https://user-images.githubusercontent.com/36999612/129199977-e03517b2-8b51-43e4-84f8-ecc5155fd8d8.png)

# Additional context
This big only shows up in fulguris browser and not in chrome.

~~No adblocker no firewall enabled.~~
It seems that when using an adblocker unwanted sites gets resolved to IP 0.0.0.0 or 127.0.0.1 and don't have any certificate (of course)
->The solution is to install a certificate on the adaway webserver or use ip-adress 0.0.0.0

**Comment by Slion** [comment]
That's odd, I wonder if something could be done in Fulguris to avoid that.

**Comment by zwmn-beep** [comment]
not interested any more
