### ISSUE TITLE
Dynamic loading of assets is broken

### ISSUE THREAD

**Issue by the-djmaze** [Slion/Fulguris#246]
# Description
Dynamic loading of CSS and Fonts is broken.
See style loading: https://github.com/the-djmaze/snappymail/blob/master/dev/boot.js#L102

# To reproduce
1. Go to https://snappymail.eu/demo/
2. See error

# Expected behavior
Just like in Firefox, Chrome, Safari etc. see a styled login screen.

# Additional context
https://github.com/the-djmaze/snappymail/issues/107
https://github.com/jamal2362/Styx/issues/74

**Comment by Slion** [comment]
Glad you could work it out.

**Comment by Slion** [comment]
Also in the future when faced with such issues you can try a WebView web browser that's not based on Fulguris, to understand if this is a WebView issue or a Fulguris issue.

**Comment by the-djmaze** [comment]
> Also in the future when faced with such issues you can try a WebView web browser that's not based on Fulguris, to understand if this is a WebView issue or a Fulguris issue.

I've used the Firefox and Chrome developer tools. They both showed "Content-Type: application/javascript".
So it was very hard to find out that the server did not return that. but the browsers did that by themselves.
Fulguris, Styx and DuckDuckGo browsers don't do that so i had to hack my way into my Android phone to find it.
