### ISSUE TITLE
Please provide the feature as I send you from email rajasaiteja3@gmail.com

### ISSUE THREAD

**Issue by Rajagithub07** [Slion/Fulguris#250]
Please provide the feature as I send you from email rajasaiteja3@gmail.com

**Comment by Rajagithub07** [comment]
Please provide app zoom out level line from 0 to 100%

**Comment by Rajagithub07** [comment]
Please provide app zoom out level line from 0 to 100%

**Comment by Slion** [comment]
Spaming is not helping your cause mate.
