### ISSUE TITLE
Add page tools on main menu

### ISSUE THREAD

**Issue by Blue2532** [Slion/Fulguris#255]
You can improve Fulguris if you add a tool feature for that let us make changes for specific web sites settings, for example if we want to see or not pictures for a web page and not to disable it globally, set JavaScript disabled for that site but have it enabled for others, view site cookies, view site source code etc.

![20211103_084816](https://user-images.githubusercontent.com/93081707/140072075-980a2a9d-5101-4114-bc87-54e4aa2f5f93.png)
![20211103_083751](https://user-images.githubusercontent.com/93081707/140072118-42865485-b4ab-4155-8ed7-3495fba20806.png)
![20211103_083825](https://user-images.githubusercontent.com/93081707/140072149-5062a4ab-04e5-4934-98e0-c6c030b3bd86.png)

**Comment by Slion** [comment]
Thanks for contributing. Yes some of that should be coming in time. Some as tab settings, some as domain settings or both maybe.

**Comment by Blue2532** [comment]
Thank you for consider my suggestion.

**Comment by Slion** [comment]
Closing this generic issue. Some cookies options have been contributed in 9af6835. JavaScript is already a domain settings option. Source code is planned in #488.
