### ISSUE TITLE
Relicensing as CPAL-1.0

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#256]
Motivated by the months long abuse of [Fulguris by Styx](https://github.com/Slion/Fulguris/issues/178#issuecomment-944982786) I'm looking at [relicensing](https://en.wikipedia.org/wiki/Software_relicensing) Fulguris to [CPAL-1.0](https://opensource.org/licenses/CPAL-1.0). This is done in the hope that future rebranding efforts would at the very least contribute to Fulguris success by enforcing prominent public attribution most likely in the form of a "Powered by Fulguris" notice on application start-up.

Now relicensing is happening one way or another. The only question is whether most of the source code is going to be relicensed or simply the parts I own sole copyright over.

I'll be trying to reach most contributors asking their permissions to relicense existing source files inherited from [Lightning](https://github.com/anthonycr/Lightning-Browser).

@anthonycr Your blessing is obviously needed. I recall trying to contact you in the past when I first started working on your code base adding keyboard shortcuts and hoping to contribute it back but somehow that was unsuccessful. Hopefully this time I can reach you. I won't even bother trying to contact other contributors if you are not happy with this. In which case I would just go ahead with partial relicensing.

@Helium314 Would you be happy with that?

## References

- [Reddit CPAL license](https://github.com/reddit-archive/reddit/blob/master/LICENSE)
- [CPAL Overview](http://oss-watch.ac.uk/resources/cpal)
- [CPAL at SPDX](https://spdx.org/licenses/CPAL-1.0.html)
- [CPAL on opensource.org](https://opensource.org/licenses/CPAL-1.0)

**Comment by jamal2362** [comment]
@Slion 

That's a lie, we were in contact for months and I gave you credits everywhere. It was obvious that it is a fork of Fulguris.

I find it very associal to claim false things. But the day will come.

**Comment by jamal2362** [comment]
Styx will be back in a few hours.

**Comment by Slion** [comment]
@jamal2362 I'm glad you are back, truly. This is really off topic here however and I'm going to delete those posts once you moved them in #257. I'm also most pleased that Fulguris credit is now at the very top of Styx README, this is definitely a step in the right direction.

**Comment by IzzySoft** [comment]
@jamal2362 of course you can add the badge back – Styx was never unlisted at my end (I always hoped for a positive outcome for all of us). I've re-enabled auto-updates as well as removed the NoSourceSince flag right now, these changes will be reflected publicly with the next sync tomorrow.

And shall we all stay objective, without attacks? We managed that quite fine in the other issue. Stéphane might not have used the "ideal diplomatic phrasing" (after all, the 3 of us are rather the practical types, aren't we, and not politicians "blowing perfumed air"). So let's work together in a friendly way if we can :heart_eyes: No need to unroll all the details again – we've already discussed and cleared out the misunderstandings, didn't we?

That said: Please count me among those people happy about your (and Styx') return! Wishing us all a cooperative and fruitful future!

**Comment by jamal2362** [comment]
@IzzySoft 

Thank you for letting me add the badge again!
I think that we regulate this in the future without dispute. There were from my side some things that were not good and that I am trying to improve now.

**Comment by jamal2362** [comment]
Closed ?
Have you discarded this idea?

**Comment by Helium314** [comment]
Sorry for the really late reply, I am still not having too much time (and what I had I put into contributing to another app, but this is has been paused for quite a while as well....)

Anyway, I'm very happy to see this is solved and there is progress again!
As for the license, I personally do not care which one is used, but most of my contributon to Fulguris is taken from Yuzu browser and thus Apache License, Version 2.0. The part I did to make it work and extend it is often not well separated from Yuzu code, so I am not sure whether I can say that "my parts" are under a different license.
