### ISSUE TITLE
[Bug] Certificate Info window won't shown completely

### ISSUE THREAD

**Issue by rustforfuture** [Slion/Fulguris#260]
Hello

The certificate info window won't shown completely.

This is probably because i set the system scaling and system text size of my device to maximum.

This is screenshot of it, as you see the date of certificate won't show.

![Screenshot_20211105_010712_net slions fulguris full playstore](https://user-images.githubusercontent.com/49192003/140437107-36d7613d-55c1-462b-a97c-d4a97afb5a89.jpg)

### To Reproduce

Set system scaling (and probably also text size of system) to maximum in system settings.

Then open an https website and tap on lock icon in url bar.

### Expected behavior

At least the certificate info window should be scrollable like styx browser or the modified version of lightning that 1DM download manager integrated it (and fixed some of its bug like this)

### Screenshots

Is in above 🌹

###Decice Info###

- EMUI Android Pie
- EMUI Android Oreo Go edition
- An unknown brand cheap Chinese android box (Android Pie)

All of them have latest version of the Fulguris (1.7.8)

-----

Thank you very much

**Comment by Slion** [comment]
This was fixed as part of #265.
