### ISSUE TITLE
Option to trim protocol and www from URL bar

### ISSUE THREAD

**Issue by rustforfuture** [Slion/Fulguris#261]
### Describe the feature you want

Please add an option to trim protocol and www from URL bar.

Like Firefox for android that by default do this.

But you can add it as an option in [Look and feel > Toolbar Shows] and don't make it default so users won't be upset.

### Is your feature request related to a problem? Please describe.

No, but it will empty more space for useful parts of url.

Because www isn't important and the fact that website has https or not is obvious with lock icon in URL bar.

Just like Firefox:

![Screenshot_20211105_005426_org mozilla firefox_beta~01](https://user-images.githubusercontent.com/49192003/140436243-b64360b5-9536-4a92-9738-c1f2ca6d047f.jpg)

--------

Thank you very much

**Comment by Slion** [comment]
This is straight forward to implement, just add a new "tool bar shows" option. We currently support:

- Domain
- URL
- Title

We need to add something like:
- Shortened URL

**Comment by jamal2362** [comment]
Examples:
![Screenshot_1640954384](https://user-images.githubusercontent.com/15986930/147826212-972955fa-d548-4cdc-9864-ce50110c547c.png)

![Screenshot_1640954405](https://user-images.githubusercontent.com/15986930/147826217-25895c00-fab4-47b0-b00b-194f03b37adf.png)
