### ISSUE TITLE
Cannot play DRM protected videos 

### ISSUE THREAD

**Issue by Kita2345** [Slion/Fulguris#268]
e.g. in https://www.tele5.de/mediathek/

**Comment by jamal2362** [comment]
Is your phone rooted ?

**Comment by Kita2345** [comment]
No

**Comment by Slion** [comment]
It works here, you have to allow that protected content request when it comes in.

**Comment by Slion** [comment]
![Screenshot_20211114-162023_Fulguris](https://user-images.githubusercontent.com/6508892/141687256-94e67527-8e36-453f-80cd-a247aaae2a0b.png)

**Comment by jamal2362** [comment]
Same. Works here.

**Comment by Slion** [comment]
@Kita2345 Closing this issue then. If you can bring more information to help us reproduce it feel free to reopen it.
