### ISSUE TITLE
User agent improvements

### ISSUE THREAD

**Issue by Helium314** [Slion/Fulguris#275]
Currently the user agent is the default WebView user agent with some specific parts removed because apparently Google doesn't allow login otherwise. The user agent still contains the phone model, which helps with identifying / tracking the user and thus might not be wanted by everyone.

I think it would be an improvement to (optionally?) do it like [FOSS Browser](https://github.com/scoute-dich/browser/blob/9d32666270a1752be903808e89e90d371eea19ad/app/src/main/java/de/baumann/browser/view/NinjaWebView.java#L568). Resulting user agent for mobile is essentially the same as Fulguris', but without the phone model.

In FOSS browser also the desktop user agent is based on this, and again I think it would be an improvement if Fulguris had something similar. The main difference is that the correct version is supplied, which could avoid some compatibility errors if users have much older or much newer WebView versions than 88.0.4324.152 (as in the current hardcoded string).

@Slion if you agree I would do a PR.

**Comment by Slion** [comment]
I have nothing against that. Here again, be aware the styx branch also contains user agent changes. Please to not merge anything to the main branch until the styx branch is merged.
