### ISSUE TITLE
Share text/link to Fulguris

### ISSUE THREAD

**Issue by Kita2345** [Slion/Fulguris#279]
User story

When we are chatting with friends, or reading mails, we are in another apps. Maybe we see some texts or links and we want to open it in this Browser.

We might want to share the text/link to this browser to search/open.

Acceptance Criteria (how do I know when I’m done?)

Open another app, select a text or link
Share the text or link
The text or link could be shared to Fulguris to search/open.

**Comment by Slion** [comment]
I'm pretty sure in some circumstances at least, app, android version, when you select text there is a context menu that opens from which you can do a web search and that should already work with Fulguris.

**Comment by Slion** [comment]
For the share to work I guess we need the following:
https://developer.android.com/training/sharing/receive
