### ISSUE TITLE
Issue with going to the previous page via the back button 

### ISSUE THREAD

**Issue by Zero3K** [Slion/Fulguris#281]
When I tap it, the page contents do not change to the previous URL's (it doesn't happen all the time though).

**Comment by Slion** [comment]
If the address is hidden it shows it. If the address bar is shown it goes back in your tab history.

**Comment by Zero3K** [comment]
I think its an issue with Chrome itself since I notice it on my PC.

**Comment by Slion** [comment]
Ho, I see what you mean. Not sure if it is with Chromium or with some websites. Sometimes you go through some funny redirections that do polute the tab history. At least with Fulguris it is somewhat easier to understand what's going on thanks to the tab animation effects. If if plays it means the back command was sent to WebView.

At some point we will implemt means to visuallize tab history to. That could help understand such issues.
