### ISSUE TITLE
Improve choice of tab when a tab is closed

### ISSUE THREAD

**Issue by Helium314** [Slion/Fulguris#291]
When closing a tab, the tab that is loaded next is not (easily) predictable, and swtiching often prefers frozen tabs over loaded ones.

So my suggested improvement in 'next tab' choice after closing a tab consists of two parts:
1. prefer non-frozen tabs. I think this makes sense because it's more likely a user wants to go back to a tab recently used instead of an "old" one (not loaded since the browser was last started)
2. use a defined order. When I have a few tabs open, open a link in background tab and press back, I don't always go to the same tab, which I find confusing. My preferred order would be the recently used order, but some users may prefer next/previous neighbours in tab list. So this could be a setting, like some desktop browsers have.

Combination of 1 and 2 might not be obvious, but for me it has use when opening one or more links in background tab and then closing current tab.

**Comment by Slion** [comment]
> When closing a tab, the tab that is loaded next is not (easily) predictable

When closing the current tab the one that replaces it should be the most recent tab you visited.

**Comment by Slion** [comment]
> When I have a few tabs open, open a link in background tab and press back, I don't always go to the same tab, which I find confusing.

That seems to be your primary issue here. Tabs opened in the background are added all the way at the back of the most recently used list and you seem to expected them just underneath the current tab. I kind of disagree with that. You can easily access tabs you just opened in the background using the newly added easy tab switcher and going forward in the list which will basically bring you all the way to the back where your background tabs have landed.

**Comment by Slion** [comment]
By aware that at some point there will be some major changes to our tab list, notably sorting and hopefully search too.
This is talked about there: #80.

**Comment by Helium314** [comment]
> When closing the current tab the one that replaces it should be the most recent tab you visited. I thought that should already be the case. I gave it a quick try and it seems to work as intended.

This is interesting, I cannot reproduce the behavior I've had earlier. I looks like you are right. Maybe there was something else involved with my problem...

**Comment by Slion** [comment]
> This is interesting, I cannot reproduce the behavior I've had earlier. I looks like you are right. Maybe there was something else involved with my problem...

Probably just you expectation with the handling of background tab opening.

**Comment by Helium314** [comment]
> Tabs opened in the background are added all the way at the back of the most recently used list and you seem to expected them just underneath the current tab.

I don't expect them under the current tab in recently used order (as it hasn't been in use ever), but I still do expect it to be opened before loading any frozen tab (at least as long as tabs can't be frozen while the browser is running)

**Comment by Slion** [comment]
Frozen status is not taken into account at all. All that matters is the order in recently used list.
