### ISSUE TITLE
Popup menu is always delayed

### ISSUE THREAD

**Issue by Helium314** [Slion/Fulguris#294]
The popup menu is supposed to show with a delay only if the keyboard is shown:
https://github.com/Slion/Fulguris/blob/67b7b31dbe1898d13ec1a22bb680dda3a433a450/app/src/main/java/acr/browser/lightning/browser/activity/BrowserActivity.kt#L780-L788

However, (at least on my device) `inputMethodManager.isActive` returns true even if the keyboard isn't showing, so the (slight but noticeable) delay always occurs.
Checking whether the keyboard is shown apparently isn't straightforward, see e.g. https://stackoverflow.com/a/6131725 and the comment that might have a solution.

(and: the comment "Open our menu with a slight delay giving enough time for our virtual keyboard to close" implies the keyboard should close, but `inputMethodManager.hideSoftInputFromWindow` isn't called)

**Comment by Slion** [comment]
Another good catch. I'm not sure why we did need that delay now.

**Comment by Slion** [comment]
On my phone the virtual keyboard does not even close when you open the menu now. Actually it closes and reopens, it's like it flashes.

**Comment by Helium314** [comment]
I tried without delay and with `inputMethodManager.hideSoftInputFromWindow`: the keyboard hides, but the popup menu is still opened on top of where the keyboard was.
With delay this does not happen (well, it did still happen exactly once in many tests, but my device is antique as you said)

**Comment by Slion** [comment]
Ho that's it. It's to avoid having the menu floating in the middle of the screen when using tool bars at the bottom, right?

**Comment by Helium314** [comment]
Yes, I think so. Only that it doesn't even try to hide the keyboard.

**Comment by Slion** [comment]
If you have a text field in focus on your webpage the keyboard should be open. When you tap the menu icon keyboard should close cause focus goes to button and the menu.
Except that's not happening in my FxTec Pro1 LOS 19.1. Habe to try other phones see what I get.

**Comment by Helium314** [comment]
So the behavior should be:
```
if (keyboard showing) {
  hide keyboard
  show popup menu (delayed by 100 ms)
} else {
  show popup menu (no delay)
```
Is this correct?

**Comment by Slion** [comment]
I think so but now I'm thinking it's mostly bullshit since it's not working and the keyboard state is a mess too. It's like when the menu opens the view underneath still has focus somehow.

**Comment by Slion** [comment]
I fixed the part where the view underneath still has the focus and thus the keyboard remain open.
Then it needs the delay otherwise the menu opens in the middle of the screen and the keyboard hides leaving the menu in the middle of the screen.
