### ISSUE TITLE
Launch from third-party app opens background tab

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#316]
Opening a tab from a third-party app when Fulguris is not running opens it in the background. 
Such new tab should open it in the foreground, much like when Fulguris is already running.

I also noticed that closing that tab sends us back to the app that opened it. Though I'm thinking this could be a feature rather than a bug.

Possible regression introduced in v1.7.25.
Related to #315 and first reported by @Helium314.

**Comment by theriel** [comment]
Remember to check both whether Fulguris is in active memory as well as when it's been closed by the user before opening the link, as these give different results: 

When it's been closed, it opens as a background tab
When it's still open, then it opens the tab list

**Comment by Slion** [comment]
> I also noticed that closing that tab sends us back to the app that opened it. Though I'm thinking this could be a feature rather than a bug.

That's indeed a feature and it will be improved by not closing the activity when closing such a new tab after Fulguris or that tab was sent to the background.

**Comment by Cwpute** [comment]
Sorry to necro this issue, but i've been regularly experiencing this bug, for several months row, but have only taken the time to report it now (sorry!).
I'm using Fdroid's 1.9.30.
