### ISSUE TITLE
Bookmarks directory return to the previous menu

### ISSUE THREAD

**Issue by Pantyhose-X** [Slion/Fulguris#318]
Bookmarks directory return to the previous menu.
People who have a lot of Bookmarks are very useful.

**Describe the solution you'd like**

- Bookmarks directory, after the first time open the website, click the Back key to return to the Bookmarks directory.

**Additional context**

https://user-images.githubusercontent.com/42504385/148888901-46bfb31e-988a-41d2-8105-a0a14cd6de18.mp4

**Comment by Slion** [comment]
It seems to be working like that here. It goes back to your bookmarks folder. Both in the [bookmarks tab](fulguris://bookmarks) and panel.

**Comment by Pantyhose-X** [comment]
> It seems to be working like that here. It goes back to your bookmarks folder. Both in the bookmarks tab and panel.

Fulguris does not have this feature.

**Comment by Slion** [comment]
@Pantyhose-X Thanks for your interest in Fulguris and your feedback.

However I'm afraid I still don't understand what this is about. As explained above it seems to work properly already.
Feel free to clarify your thought. You could also try it in Fulguris and make a video too to show us what happens.

**Comment by Pantyhose-X** [comment]
@Slion Returns the 'Pictures Below' bookmark folder list.
![3](https://user-images.githubusercontent.com/42504385/149140273-54ae6578-3fcb-4507-b9ee-47f5ff3f1b21.jpg)

Do not Return to Homepage bookmarks.
Not working 

https://user-images.githubusercontent.com/42504385/149140382-046be12a-edf8-47f8-b7a8-441b0b0436ed.mp4

**Comment by Slion** [comment]
I understand now. To get it to work the way you want you should use the bookmarks page from: fulguris://bookmarks.
You can also set your homepage to bookmarks from Setting > General > Homepage.
Hope that helps.

**Comment by Pantyhose-X** [comment]
> I understand now. To get it to work the way you want you should use the bookmarks page from: fulguris://bookmarks. You can also set your homepage to bookmarks from Setting > General > Homepage. Hope that helps.


What I want is to return bookmarks list like video. I don't want to go back to homepage bookmarks

**Comment by Slion** [comment]
> What I want is to return bookmarks list like video. I don't want to go back to homepage bookmarks

The bookmarks page is almost exactly like the bookmarks list. Well, it is a bookmark list. Why would that not be satisfactory for you? Is it because it does not provide the bookmark editor feature compared to the drawer? I'm afraid you will have to make do with that until #200 is implemented.

**Comment by Slion** [comment]
Here is what it looks like:
https://www.youtube.com/watch?v=b5hjvBywWMg
