### ISSUE TITLE
visiting page redirects to data:text/html;charset=utf-8;base64

### ISSUE THREAD

**Issue by Kita2345** [Slion/Fulguris#342]
Go to https://dopiaza.org/tools/datauri/examples/index.php

See error

**Comment by Slion** [comment]
Works for me:
![image](https://user-images.githubusercontent.com/6508892/150696660-7adf648f-f8a0-4c33-8be3-f78f97c7294d.png)

What's your device, OS and WebView?

**Comment by Kita2345** [comment]
Also this https://tweakers.net/reviews/8806/harvest-moon-one-world-beter-maar-nog-steeds-tegenvallend.html

**Comment by Kita2345** [comment]
ZenFone Max Pro (M2)
Android 9
97.0.4692.98

**Comment by Slion** [comment]
Works here too. Though I tested on Windows 11 only:
![image](https://user-images.githubusercontent.com/6508892/150696976-00fbaa5c-c4ca-46da-87e9-f1cd5db941f4.png)

**Comment by Slion** [comment]
Your WebView is up to date so I'm not sure what could be the issue here. Do you have content blocker enabled?

**Comment by Slion** [comment]
Works here with content blocker too so I guess that's not the problem.

**Comment by Kita2345** [comment]
Works here if Request save data disabled
so I will close this issue
