### ISSUE TITLE
Show link in long press menu

### ISSUE THREAD

**Issue by Helium314** [Slion/Fulguris#349]
In older versions, long pressing a link showed a menu with the link ed URL on top. This menu was improved recently, but now the link is not shown any more. So in usually the only way of knowing where a link goes (before clicking it) is by copying the link and pasting it somewhere.

Would it be possible to show the link again in the menu?
(same goes for images)

**Comment by Slion** [comment]
Most links are cut short cause too long to display so it never really worked well anyway. Though you could see the domain of the link I guess.

**Comment by Helium314** [comment]
Well, it was quite large font size, but used two lines. If the font size of the link would be smaller (similar to the text) and could be spread over multiple lines it could work, maybe even show the whole link in most cases. I guess there still needs to be on how much text is displayed, otherwise long links will break the layout.

Clicking the link text could act like the "copy link" button. This functionality is not obvious, but I think users who want to copy the link would try to select the link text and thus notice it anyway.

**Comment by Helium314** [comment]
I had a look at this, but found that all lines (i.e. `DialogItem`s) can only have a resource string as text... so this is a bit more work than I had hoped.

**Comment by Slion** [comment]
> more work

That sounds indeed like a lot more work than writing a whole adblocker 😁 Sorry, just being cheeky. I'm curently enjoying a bit of a break from the project after an intense couple of months. I'll be back soon enough.

**Comment by Helium314** [comment]
Well, it could have been as easy as setting the title...

**Comment by Slion** [comment]
Close as duplicate from #362, even though this one came first 😁
