### ISSUE TITLE
Website opening problem.

### ISSUE THREAD

**Issue by YuriV1king** [Slion/Fulguris#356]
I can not access this site https://new.moy.magnit.ru/. 
A window pops up with the text "Forbidden". No problem on PC.

**Comment by YuriV1king** [comment]
Hey Stephane! One of the options you suggested turned out to be correct. It's all about changing the user agent. I hid the device and it caused an error. This is not a browser error and that's good. Thanks!

**Comment by Slion** [comment]
@Helium314 you might be interested by this feedback about hidden device in user agent causing problem on that web site.
The solution was to use the default user agent instead.

**Comment by Helium314** [comment]
This is interesting, I can't reproduce it.

@YuriV1king would you mind sharing your user agent with 'Hide Device' enabled?
Maybe the string is broken... it should be something like:
Mozilla/5.0 (Linux; Android `<android version>`) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/`<webview version>` Mobile Safari/537.36

**Comment by YuriV1king** [comment]
**Helium314**, Strange story, but I hid the device again and tried to open the page and ... the site miraculously opened). So, I don't know if I should show you my user agent now. It is difficult now to say whether it was a mistake.

**Comment by Slion** [comment]
Might have been a temporary problem on that web site.
