### ISSUE TITLE
When I go back from reading mode, I want to stay in incognito mode.

### ISSUE THREAD

**Issue by Yuri-VK** [Slion/Fulguris#369]
When in incognito mode, if you open a page on a site in read mode and then want to read the page original, why does it move to normal browser mode when you go back (more precisely, I switch to the default mode of the browser, but the page remains in incognito mode), but not stay in private mode? Is this a bug or a feature of the browser? It turns out a lot of extra movements. This is not a complaint, I'm just wondering why?

**Comment by Slion** [comment]
Reading mode currently does not work with incognito mode so I just disabled it. Going in reading mode takes you out of incognito. Is that ok for you? How bad do you want reading mode in incognito?
