### ISSUE TITLE
Incognito mode startup time has increased.

### ISSUE THREAD

**Issue by Yuri-VK** [Slion/Fulguris#370]
I noticed that the launch time of the incognito mode increased by two to three seconds compared to what it was before. What influenced this behavior? Device: ZTE Blade V9 vita, OS: Android 8.1

**Comment by Slion** [comment]
No idea really.

**Comment by Yuri-VK** [comment]
Я думаю эту проблему нужно закрыть, поскольку я скорее всего не прав.

**Comment by Slion** [comment]
Could also have been caused by that faulty WebView you were using.

**Comment by Yuri-VK** [comment]
Regardless, I don't think it's defective. All applications work correctly (perfectly) with it.
