### ISSUE TITLE
Flickering (flashes) on the screen when clicking on search results

### ISSUE THREAD

**Issue by Yuri-VK** [Slion/Fulguris#372]
# Description
Clicking on search results generated by the Google search engine, there are light flashes on the screen.

# Environment
 - Device: [Smartphone]
 - OS: [Android 8.1]

# To reproduce
Steps to reproduce the behaviour:
Enter a search query on the Google search page, wait for the results, then click on any of the displayed search results. See that there is a flash (flickering of the screen) at the moment of pressing.

# Expected behaviour
When you click on any of the returned search results in the Google search engine, there should not be any flashes of light (screen flicker)

# Additional context
I can't provide screenshots (it's hard to implement). I want to note that nothing like this happens in version 1.8.6.

**Comment by Slion** [comment]
Weird that it would be new to 1.8.7. Can you do a screen recording?

**Comment by Yuri-VK** [comment]
> Weird that it would be new to 1.8.7. Can you do a screen recording? Did you change or update your WebView?

WebView was the same in two versions of the browser and updated to the latest version (with a number at the end of 127)

**Comment by Slion** [comment]
WebView issue.

**Comment by Yuri-VK** [comment]
Maybe this issue can be somehow merged with this question, since the problem lies elsewhere and no solution has been found.
