### ISSUE TITLE
uploadrar.com

### ISSUE THREAD

**Issue by urfausto** [Slion/Fulguris#393]
# Description
website shows anti-adblock frame even if default ad-blocker is disabled (and never been enabled)

# Environment
 - Device: dipper
 - OS: lineage
 - Version: 19.1

# To reproduce
Steps to reproduce the behaviour:
1. Go to https://uploadrar.com/ut0r3yh638v5
2. Click on 'Free download'
3. Wait on the page for the warning to pop up

# Expected behaviour
No anti-adblocker warning showing up

**Comment by brnwlshubh** [comment]
@urfausto Working for me Here is the direct
[Link](https://fs20.uploadrar.com:183/d/mxs5fkljappay775b6hov24nrvajbdveup6jitc3bsnvcdzh3wqsiszpk7dk7sgdmjaupthx/TikTok_25.7.3_arm7_Mod.apk)

**Comment by Helium314** [comment]
Also working for me, Lineage 16.0

**Comment by urfausto** [comment]
> @urfausto Working for me Here is the direct
> [Link](https://fs20.uploadrar.com:183/d/mxs5fkljappay775b6hov24nrvajbdveup6jitc3bsnvcdzh3wqsiszpk7dk7sgdmjaupthx/TikTok_25.7.3_arm7_Mod.apk)

thanks but i just wanted to check if it's a bug... i can't figure out why i get this adblock popup message... i have some installed apps like magisk or exposd module, might be that?

**Comment by urfausto** [comment]
tested with https://play.google.com/store/apps/details?id=com.cookiejarapps.android.smartcookieweb and i keep getting the same issue...

**Comment by urfausto** [comment]
ok i've finally managed to make it working: it was an issue with **jasi patcher**. i'v reverted the changes with the same app and now everything is back to normal so this popup does not appear anymore.
