### ISSUE TITLE
Inquiry of progress or plans of integration and (re-)releases of Styx browser

### ISSUE THREAD

**Issue by R0M4N0F5K7** [Slion/Fulguris#396]
Hey guys, I hope it's okay to ask, I've been waiting patiently for more than a year now, but it seems like any discussion about Styx Browser died down.  Did it not work out in the end? I see that the Styx build is still present and marked as passing, but I can't find any new Styx releases, and it's been a while since @jamal2362  did any commits here.
Did it not work out in the end?
Being a web view browser, I suppose it won't become unusable concerning security risks as long as web view is updated (right?), but I, and surprisingly many people around me really liked the project and hope for it to go on/return.

(Sorry again for posting here, but as the Styx repo was closed after at that critique I thought this would be the best official place to ask following [the initial discussion](https://github.com/Slion/Fulguris/issues/257) and [progress of integration](https://github.com/Slion/Fulguris/issues/265) also documented here)

**Comment by Slion** [comment]
> Did it not work out in the end?

Depends which way you look at it I guess. A few features from Styx were integrated back into the Fulguris code base. The Fulguris code base was modified to enable Styx and possibly other rebrands to be released along side Fulguris under the terms of the CPAL license. So in this respect it was a success. However as far as I know Styx was never rereleased from the Fulguris code base. That makes it a failure I guess.

> Being a web view browser, I suppose it won't become unusable concerning security risks as long as web view is updated 

That is correct.

> I, and surprisingly many people around me really liked the project and hope for it to go on/return.

Which aspect of Styx do you like that is missing from Fulguris?

**Comment by Slion** [comment]
Closing as this is a discussion rather than an actual issue and no further action is required. Feel free to keep on discussing though.
