### ISSUE TITLE
JavaScript desktop mode rework

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#401]
Since we tracked down our desktop mode issues to the fact that wide viewport mode was being enabled we should consider reworking our JavaScript desktop mode viewport manipulation. In fact desktop mode should now simply work by just changing the user agent. Providing that wide viewport is disabled.

Though we should still consider using that dekstop width settings to offer a desktop mode with a width above the actual viewport width.
Consider changing the desktop width configuration settings unit from pixels to percentage of the actual viewport.
Consider removing desktop width settings altogether.

**Comment by Imerion** [comment]
Great to see the width setting was kept. Having these settings visible in the UI was my main reason for choosing this excellent browser. I have experimented with it and in order to always get a real desktop page on my phone I usually need to increase it to at least 1024. Many other browsers sadly don't have this feature and on those the desktop mode often just shows a tablet-like page instead. And only changing the user agent doesn't help at all of course, in that case I still get crappy mobile layouts for 99% of all pages.

**Comment by Slion** [comment]
> Great to see the width setting was kept

You got lucky there, it was a close call 😁
I hope it still works for you. Desktop width is now a percentage of your actual viewport width rather than expressed in pixels as before. By default it is set to 100% and that means only the user agent is changed. When set to other than 100% JavaScript code is injected to specifiy a virtual width resulting in that zoomed out effect, much like before, just a bit more optimized.

The wide desktop settings option was removed from the settings. It is now only turned on when we need it which is when the desktop mode injects JavaScript.

That should be part of the next release which will be v1.9.x I guess.
@Imerion Which variants are you using: Play, Download or F-Droid, all of them?
I'm asking cause I would love to get feedback on those changes before I push it to all release channels.

As currently setup desktop width can be set from 100% to 300% though I'm guessing most people would only like to set it to 120% or 150%. I wonder if it should be set to 120% by default rather than 100%. When updating it's recommanded you adjust the settings otherwise in your case it's going to use 1024% rather than pixels.

**Comment by Imerion** [comment]
@Slion Thanks for the background info! I am using the version from F-Droid and I'd be happy to test this if it can be of help. I can download a separate version not from F-Droid too if you have a beta-release or such.

Thanks for making an awesome browser by the way! Without doubt the one that fit my needs the best thanks to all features and options. :)

**Comment by Slion** [comment]
Usually the Download variant is published first then Google Play when no major issues are found. I'm still new to the F-Droid release process so it could be updated last. I'll notify when the new version is out, thanks for volunteering.

**Comment by Slion** [comment]
@Imerion I just [released v1.8.10](https://slions.net/resources/fulguris.10/).

**Comment by Imerion** [comment]
@Slion Thanks for letting me know! I just tested it, but the desktop mode seems to have a few issues. Setting the width to around 150% makes it possible to get a wide enough view, but it always seem to start too much zoomed out. Previously the entire page was framed in the window with no "black" area around, but now it always seem to start showing a page zoomed out so half of the screen displays the page and the other half is just black.

Also, on many pages the desktop mode won't work at all, only showing the mobile page no matter what I set the width slider to.

I tried disabling overview mode but that doesn't solve the problem, it only starts with the page view zoomed in but the black areas on the sides remain.

**Comment by Slion** [comment]
Try with 101% and see what you get.
For the sites that are not working anymore could you give me some URLs to try them out?

**Comment by Imerion** [comment]
101% gives the same result, though for some reason it starts in a mobile view and then slowly zoom out until it looks like this:
![yourdocument](https://user-images.githubusercontent.com/16926509/194772497-c47a93ea-25c9-4288-ae1e-bebd09b77c3d.png)

Pages that don't display a desktop mode at all include this Github page, www.nintendoeverything.com and www.nintendolife.com.

I should also mention I tried this with a clean install, so no old options should be affecting things.

**Comment by Slion** [comment]
@Imerion @HemanthJabalpuri 
I just published v1.8.11.
Hopefully it fixes those regression issues you've been having.

**Comment by HemanthJabalpuri** [comment]
> @Imerion @HemanthJabalpuri I just published v1.8.11 download variant. Hopefully it fixes those regression issues you've been having. Just let me know how it goes for you so that I can decide to do a new F-Droid release.

It works fine, just tested this issues page only for now. But updating from 1.8.8 to 1.8.11 made Force Closes at app starting, so I cleared data and it's fine now. Can't able to take logs since I am at work.

Thanks for quick fix :)

**Comment by Imerion** [comment]
I can also confirm it works well now! Thanks a lot for taking your time with this!

I did notice one thing though: if Force Zoom is enabled desktop mode stops working. I can see that it isn't necessary together with desktop mode as it always allows zooming in and out by design, so maybe that option should be disabled when desktop mode is active to not confuse people.

I also needed to delete old data to make the browser start after updating, as mentioned above, but that was easily done.

**Comment by Slion** [comment]
Needing clear data is really bad. It means your lose all your sessions and tabs. I did not have that issue funny enough.

Yes force zoom does break desktop mode. I was thinking I should remove it already or as you said I should at least disable it when desktop mode is engaged.

**Comment by Slion** [comment]
I can reproduce the crash on start-up. Basically it happens if your current tab is in desktop mode and you had earlier changed the desktop width in the settings. I'll do another release to adress that and we should be good to go.

**Comment by Slion** [comment]
Just pushed a new version.

**Comment by Imerion** [comment]
Awesome! Can confirm it doesn't crash after update now.

**Comment by HemanthJabalpuri** [comment]
@Slion 
Desktop mode in 1.8.12 is not working as expected like in 1.8.8. It doesn't show things that are added/changed when Desktop mode is activated.
with 1.8.8
![Screenshot_2022-11-01-20-28-23-75](https://user-images.githubusercontent.com/39197123/199264808-69816047-f21c-479f-9ddf-1e5a24921859.jpg)
with 1.8.12
![Screenshot_2022-11-01-20-28-18-01](https://user-images.githubusercontent.com/39197123/199264905-122f182e-db78-4b88-bbe8-bd945b74254b.jpg)

**Comment by Slion** [comment]
Did you try to adjust the desktop width in settings?

**Comment by HemanthJabalpuri** [comment]
> Did you try to adjust the desktop width in settings?

Seems like setting the Desktop width(Settings -> Look & feel -> Portrait) to 300% makes it work in my device.
