### ISSUE TITLE
Content control EasyList and EasyPrivacy download error

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#404]
Both EasyList and EasyPrivacy can't be reached anymore it seems.

**Comment by Helium314** [comment]
Well they can be reached, but are very slow to load. Try https://easylist.to/easylist/easylist.txt
I already tried increasing the timeout for the request, but no success there...

**Comment by Slion** [comment]
Damn that is slow…

**Comment by Helium314** [comment]
Maybe we can alternatively download from https://github.com/easylist/easylist, though I'd need to read on how to get a list equivalent to the current ones.

**Comment by Slion** [comment]
Maybe we could host the lists somewhere else somehow.

**Comment by Slion** [comment]
I'm still getting timeouts 🤦

**Comment by Helium314** [comment]
Hm. For me it fixed the download 2 days ago...

**Comment by Slion** [comment]
Let's keep in eye on it. I guess we could increase the timeout some more.

**Comment by Slion** [comment]
Have not had issues with that in a while. Looks like that fixed it.
