### ISSUE TITLE
Desktop mode broken in 1.8.10_178

### ISSUE THREAD

**Issue by HemanthJabalpuri** [Slion/Fulguris#407]
# Description
Desktop mode broken in 1.8.10_178 but works fine with 1.8.8_176

# Environment
 - Device: Realme C12 (RMX2189)
 - OS: Android 10 (Realme UI 1.0)
 - Version: 1.8.10_178

# To reproduce
Steps to reproduce the behaviour:
1. Go to URL https://github.com/Slion/Fulguris/issues
2. Enable Web page -> Desktop
3. We can see that page is still mobile version

# Expected behaviour
It needs to change to Desktop mode, but thats not happening.

# Screenshots
N.A

**Comment by HemanthJabalpuri** [comment]
seems like discussion is going on at 
https://github.com/Slion/Fulguris/issues/401

**Comment by Slion** [comment]
Thanks for reporting this. Yes this is the reason why v1.8.10 has not been released on Google Play or F-Droid. I've already pushed a fix for it. See: https://github.com/Slion/Fulguris/commit/fd51ce07980bab690de959a9c585d1d081047012
