### ISSUE TITLE
Allow to always trust on locally installed CA certs.

### ISSUE THREAD

**Issue by luckkmaxx** [Slion/Fulguris#421]
**Is your feature request related to a problem? Please describe.**
The problem is that every new session asks if I trust on my self signed certificates, wich has CA installed on device.

**Describe the solution you'd like**
It could be great to ALWAYS trust on these type of certificates. 

**Describe alternatives you've considered**
Maybe a hidden feature, who trust on installed CA's. Just like Firefox does.

**Additional context**
Self signed certs are made with mkcert

**Comment by Slion** [comment]
Thanks for reporting that issue. You did send an e-mail about it too, right?

Unfortunately I don't have a solution for it. At the very least we should have an option to stop asking if you trust it for that domain. But even that would required that #159 be implemented.

**Comment by luckkmaxx** [comment]
Yes I did LOL.
Currently there is an option wich I didnt saw to disable confirmation for all untrusted certs and it only shows an advice at bottom: "Untrusted certificate" or similar (I see it in spanish).
This could be enough for now, to avoid the annoying messages on every new session. And if you implement #159 so we can set this for each domain, subdomain, or url (disabling the advise at bottom of course).
This could be a workaround for this app, and as I have installed my CA anyway for other services, this wouldnt be a security risk.

**Comment by luckkmaxx** [comment]
Anyway, I thought about that other FOSS projects based on firefox has implemented this. so as far as i know, it code could be taken from there, right?

**Comment by Slion** [comment]
Thanks for the pointer that could help.

It looks like WebView should be able to do that:
https://stackoverflow.com/questions/15588851/android-webview-with-client-certificate

Glad you found an acceptable workaround.

**Comment by luckkmaxx** [comment]
> It looks like WebView should be able to do that
Sorry, whats the point of this? Does it mean there could be a chance to add the feature?

**Comment by Slion** [comment]
> Sorry, whats the point of this? Does it mean there could be a chance to add the feature?

Exactly, just documenting for developers to be able to get working on it.

**Comment by luckkmaxx** [comment]
Nice! Thanks for all!

**Comment by xinstein** [comment]
+1 vote for this feature.
It's not safe to just ignore the warning since I can't distinguish between false alarm and real mitm attack.
I switched to this awesome browser from chromium which trusts system installed ca certs. Chromium is a great browser despite it being too googlish.

**Comment by luckkmaxx** [comment]
> Chromium is a great browser despite it being too googlish.

Give a try to Bromite. Allow CA certs is a hidden flag there.

**Comment by xinstein** [comment]
> > Chromium is a great browser despite it being too googlish.
> 
> Give a try to Bromite. Allow CA certs is a hidden flag there.

Thanks a lot!

But one thing is bugging me: the apk for bromite is twice as big as chromium, which in turn is already ten times as big as fulguris

**Comment by luckkmaxx** [comment]
I have found Styx Browser, wich is a Fulguris fork. It has some added features, and I think it trusts user CA by default.

**Comment by Slion** [comment]
I wonder if their might be an easy fix:
https://developer.android.com/training/articles/security-config

See that bit:
```
<base-config cleartextTrafficPermitted="true">
    <trust-anchors>
        <certificates src="system" />
        <certificates src="user" />
    </trust-anchors>
</base-config>
```

**Comment by xinstein** [comment]
> Could be an easy fix: https://developer.android.com/training/articles/security-config
> 
> See that bit:
> 
> ```
> <base-config cleartextTrafficPermitted="true">
>     <trust-anchors>
>         <certificates src="system" />
>         <certificates src="user" />
>     </trust-anchors>
> </base-config>
> ```

Is it included in 1.8.26 ? I tried but it still gives the untrusted warning.

**Comment by Slion** [comment]
Yes it should have been fixed in v1.8.26.
I'll reopen the issue then. Thanks for the feedback.

**Comment by Slion** [comment]
I forgot the bit where it needs to be added to the manifest. I'll try do another release soon.

**Comment by Slion** [comment]
@xinstein Give it a try with v1.8.27

**Comment by xinstein** [comment]
> @xinstein Give it a try with v1.8.27

1.8.27 works great, thank you! Now I can finally use it as a daily browser

**Comment by Slion** [comment]
Thank you for your contributions and patience.
