### ISSUE TITLE
Cookie not saved on a fresh install

### ISSUE THREAD

**Issue by Nriver** [Slion/Fulguris#436]
# Description
I have login to [trilium](https://github.com/zadam/trilium) server, then restart the browser. Then the login cookie seem to be lost and I had to login every time I restart the app.

**Comment by Slion** [comment]
Which device and WebView version?

**Comment by Nriver** [comment]
RMX3366 from Realme. The WebView is 109.0.5414.117.

**Comment by Nriver** [comment]
I tried the latest version. And this seems to be fixed now.
