### ISSUE TITLE
Bookmark not editable

### ISSUE THREAD

**Issue by Nriver** [Slion/Fulguris#437]
# Description
Install Gboard and edit the bookmark inside Fulguris, the popup window disappears as I try to edit the bookmark.

**Comment by Slion** [comment]
That's odd, seems to work fine here. Which device?

**Comment by Nriver** [comment]
https://user-images.githubusercontent.com/6752679/219601691-7f257b1c-ea33-4ab8-92fb-a3dc34eeb94c.mp4

RMX3366 from Realme.

**Comment by Nriver** [comment]
Other popup input like `Download location`, `User agent` in setting works fine.

**Comment by Nriver** [comment]
This still exists in the latest version.

**Comment by Slion** [comment]
Which Android version?

**Comment by Nriver** [comment]
It's android 11

**Comment by Nriver** [comment]
I think this is the cause:

https://github.com/Slion/Fulguris/blob/ea08d9523da2c9b1aa1d69c95a15ac4bf37df04b/app/src/main/java/acr/browser/lightning/dialog/BrowserDialog.kt#L267C12-L267C12

When the keyboard pop out, the dialog get resized a little bit. By commenting out that line of code. The dialog will not dismiss immediately after keyboard shows up.

The UI is shrunked a little bit, part of the text is not shown correctly. 
![1](https://github.com/Slion/Fulguris/assets/6752679/d6c03e5f-5dd7-4b77-8ced-e3c4795a54b3)

Not sure why there is a candidate word selection box. It's a fresh install, I haven't input anything yet.

**Comment by Nriver** [comment]
The keyboard app is [Gboard](https://play.google.com/store/apps/details?id=com.google.android.inputmethod.latin&hl=en_US)

**Comment by Slion** [comment]
> Not sure why there is a candidate word selection box. It's a fresh install, I haven't input anything yet.

By default there is a Fulguris bookmark folder.

**Comment by Slion** [comment]
Nice, looks like you found the cause. Now we have to find a proper fix.

**Comment by Slion** [comment]
Possible solutions to our layout issues:
https://stackoverflow.com/questions/68469681
https://stackoverflow.com/questions/68818202/animatedvisibility-doesnt-expand-height-in-dialog-in-jetpack-compose/68818540#68818540

**Comment by Slion** [comment]
@Nriver Could you check that it works  for you in v1.9.10?
It's already available for [download on slions.net](https://slions.net/resources/fulguris.10/updates#resource-update-272).

**Comment by Nriver** [comment]
The keyboard is working. The UI is shrunked a little bit, but it's usable now. Thank you.

**Comment by Slion** [comment]
> The keyboard is working. The UI is shrunked a little bit, but it's usable now. Thank you.

I think the dialog would need to be redesigned. That should do for now though.
