### ISSUE TITLE
Close a new tab that opens by searching for text

### ISSUE THREAD

**Issue by chwt163** [Slion/Fulguris#439]
Opening a web page, copying a piece of text and searching will open a new tab, then close the new tab, the browser should close the new tab and return to the original tab, but the Fulguris program minimizes it

**Comment by chwt163** [comment]
> It's not clear to me what's your isssue. You can configure when new tabs are opened from the Settings > General > Tabs.

Compare again：
settings-about-application version.
Browse instruments to create a new tab and open this URL: https://slions.net/resources/fulguris.10/, close this tab, browsing instruments will be minimized, not in the foreground.

**Comment by Slion** [comment]
I think I understand what you mean. I can't reproduce it though. The tab is closed and the previous tab is displayed. Fulguris remain in foreground.

**Comment by chwt163** [comment]
huawei Phone: HONOR BKL-AL20(BKL-AL20)
CPU ABI: arm64-v8a 
Android Version: 10 API29
WebView Impl: com.google.android.webview
WebView Version: 110.0.5481.153(548115333)

**Comment by chwt163** [comment]
In my case, fulguris' new tab, by default, after the current tab, this bug will appear, if the new tab is set before the current tab, there is no problem.

**Comment by chwt163** [comment]
Another question, which can also be regarded as advice. If you create multiple new tabs in the background, then choose to browse through one of the new tabs, and then use the phone's back button to close the new tab, Fulguris will return to the original tab, which I think can be optimized to let Fulguris automatically activate the next new tab in order.

**Comment by chwt163** [comment]
Another question, which can also be regarded as advice. If you create multiple new tabs in the background, then choose to browse through one of the new tabs, and then use the phone's back button to close the new tab, Fulguris will return to the original tab, which I think can be optimized to let Fulguris automatically activate the next new tab in order.

**Comment by Slion** [comment]
If you close a tab it switches to the previous tab.
