### ISSUE TITLE
Auto dark mode setting

### ISSUE THREAD

**Issue by dessalines** [Slion/Fulguris#445]
**Is your feature request related to a problem? Please describe.**

Most websites do not have dark mode detection. Luckily I see that fulguris does have a *manual dark mode* in it's web page options, but this needs manual triggering. 

**Describe the solution you'd like**

Add an option in the settings to use this dark override by default on all new and maybe current tabs when your android system is in dark mode.

**Comment by Slion** [comment]
Settings / General / Force dark mode

**Comment by dessalines** [comment]
That seems to be forcing dark mode, even when my android system is in light mode. I'm suggesting it follow the system.

**Comment by not-programmer98** [comment]
Yeah this the the bromite behavior and I'm really missing it

**Comment by G-i-o** [comment]
> Settings / General / Force dark mode

I don't see that setting there. Only under > Web Page > Dark

However, this needs to be selected each time opening links in new tabs and it's annoying.

Maybe there could be an option to add an icon on the address bar, if coding of a general option takes too long?
That way at least one doesn't have to click thrice each time a new tab is opened.

Thanks! :pray:

**Comment by Slion** [comment]
It's now part of the domain settings.
From the website you want to adjust settings for go to:
Menu / Options / Domain / Force dark mode  and to Override and Force dark mode.

**Comment by Slion** [comment]
Yeah you need to do it once for each domain where you want force dark mode or you could just set the default domain settings to force dark mode if you want to use that for all domains.

**Comment by G-i-o** [comment]
How can that be done? I would very gladly like to set it up once for all as over
90% of the sites I visit don't have dark mode.

Thanks.

**Comment by Slion** [comment]
Settings / Domain / Default domain settings
Or through Options / Domain / Parent until you reach Default domain settings.

**Comment by G-i-o** [comment]
My gosh! I have no idea how I could have missed that.

Thanks a lot. My finger will be ever so happy.
