### ISSUE TITLE
Browser crash

### ISSUE THREAD

**Issue by UcraNerd** [Slion/Fulguris#448]
# Description
Due to unknown reasons (for me), when i open the browser with wi-fi active, the browser crashes

# Environment
 - Device: [SM-J600FN]
 - OS: [Android 10]
 - Version: [1.8.17]

# To reproduce
Steps to reproduce the behaviour:
1. Force stop the app
2. Make sure the wi-fi is active
3. Open the app and wait some seconds until it closes and this android pop-up shows:

![Screenshot_20230329-173612_Kvaesitso_1.jpg](https://user-images.githubusercontent.com/102480084/228592005-ba802220-98fc-4658-8b95-d4e40afc62b8.jpg)

# Expected behaviour
No crashes...

# Additional context
```
java.util.regex.PatternSyntaxException: Unrecognized backslash escape sequence in pattern near index 76
^https?:\/\/[0-9a-z]{3,12}\.(digital|website|life|guru|space)\/[a-z0-9]{6,}\
                                                                            ^
	at java.util.regex.Pattern.compileImpl(Native Method)
	at java.util.regex.Pattern.compile(Pattern.java:1433)
	at java.util.regex.Pattern.<init>(Pattern.java:1408)
	at java.util.regex.Pattern.compile(Pattern.java:992)
	at b7.c.<init>(SourceFile:2)
	at c6.j.<init>(SourceFile:2)
	at b6.a.a(SourceFile:28)
	at b.i.b(SourceFile:40)
	at b.i.h(SourceFile:31)
	at b.i.a(SourceFile:3)
	at b.i$b.h(SourceFile:4)
	at m6.a.j(SourceFile:2)
	at c7.f0.run(Unknown Source:86)
	at c7.m0.U(SourceFile:4)
	at h4.d.C(SourceFile:7)
	at b.f$a.h(SourceFile:1)
	at m6.a.j(SourceFile:2)
	at c7.f0.run(Unknown Source:86)
	at i7.a$a.run(SourceFile:9)

```

**Comment by UcraNerd** [comment]
chat gpt says that the "\" in the end of this text "https?:\/\/[0-9a-z]{3,12}\.(digital|website|life|guru|space)\/[a-z0-9]{6,}\" is the problem.

Original reponse:

`It looks like the crash report is indicating that there is a problem with a regular expression pattern that was being used in the code of the Android app.

The error message specifically says that there is an unrecognized backslash escape sequence in the regular expression pattern, which caused the pattern to fail to compile.

The regular expression pattern in question is trying to match URLs that have a specific format. The pattern is:

css

^https?:\/\/[0-9a-z]{3,12}\.(digital|website|life|guru|space)\/[a-z0-9]{6,}\

The backslash before the last character in the pattern (\) is what's causing the error. In regular expressions, a backslash is often used to escape certain characters that have special meaning, such as the dot (.) or the forward slash (/). However, in this case, the backslash is being used to escape the final character in the pattern, which is itself a backslash. Since the backslash is not a special character that needs to be escaped in this context, the pattern compiler is throwing an error.

To fix the problem, the backslash before the final character in the pattern should be removed:

css

^https?:\/\/[0-9a-z]{3,12}\.(digital|website|life|guru|space)\/[a-z0-9]{6,}

This should allow the regular expression pattern to compile correctly and match the desired URLs.`

**Comment by Slion** [comment]
From the Discord channel: 
Make sure you upgrade to v1.8.18 ASAP it fixes a crash on startup due to malformed ad blocker filter file.
Until you upgrade please disable the ad blocker to prevent the crash.
If you are already victim of that crash you can still start Fulguris by enabling flight mode to disable the internet connection.
V1.8.18 is available for download. The Google Play variant should become available over night. Not sure how long it takes for the F-Droid variant to be released. Up to a week I think.
Google rejected the app update 🤣 those guys are really clueless. I mean it's the  same app as before...

**Comment by UcraNerd** [comment]
> 

hahaha, thanks!
