### ISSUE TITLE
Fulguris crashes 1.8.17 F-Droid

### ISSUE THREAD

**Issue by laberlaib** [Slion/Fulguris#449]
Hi,
my Fulguris 1.8.17 from F-Droid keeps on crashing since yesterday.

I saw that there is a 1.8.18 with a bugfix on slion.net but if I install it, it does not overwrite my F-Droid version so that I lose all my bookmarks and the configuration.
1) is there a way to access bookmarks & configuration manually e.g. from the file system?
2) Can I expect a 1.8.18 in F-Droid soon, so patience is the key?

Add: It crashes straight after/during startup: You can see the addressbar but before any content is shown/loaded, the crash happens.

Coming from lightning browser, I cannot live without the sliding-feature for bookmarks & tabs.

Greetings
laberlaib

**Comment by Slion** [comment]
See: https://github.com/Slion/Fulguris/issues/448#issuecomment-1489057952

**Comment by laberlaib** [comment]
Ah, sorry for doublepost. I am not to firm of github and as the closed issues are not shown directly I did not see the soution.

**Comment by Helium314** [comment]
Unfortunately you will very likely have to wait for the F-Droid update. Currently they seem to have some issues, and last updates were about 2 weeks ago... no idea how long it will take until updates continue.

But either using github version for a while, or disabling internet when starting Fulguris are working around the crash.
Or you disable easylist, which is where the bad filter seems to be coming from (don't forget to enable it after the next Fulguris update).
