### ISSUE TITLE
Swipe on topbar to change tab

### ISSUE THREAD

**Issue by GameOverFlowChart** [Slion/Fulguris#450]
I'm missing the feature to swipe left or right on the top bar to jump to the previous / next tab in the list. It's a really useful feature which chromium based browsers have.

**Comment by PalmTamino** [comment]
Yes, but then also add when being on the last tab to be able to swipe left to create a new tab, like on iOS.

**Comment by Slion** [comment]
On Fulguris by default you don't create tab explicitly. They are created implicitly for you. However you can change the settings to your liking of course.

**Comment by Slion** [comment]
This feature would conflict with the scrolling of the tab title. Not a deal breaker though.

**Comment by PalmTamino** [comment]
> This feature would conflict with the scrolling of the tab title. Not a deal breaker though.

Yeah, could u please make it possible to disable that feature? Good navigation is way more important for me, for example.

**Comment by GameOverFlowChart** [comment]
> This feature would conflict with the scrolling of the tab title. Not a deal breaker though.

I have the tabs at the top disabled the suggested feature might be disabled if the tab row is used.

**Comment by Slion** [comment]
Duplicate of #296.
