### ISSUE TITLE
Cookies leak into incognito mode on Android 8

### ISSUE THREAD

**Issue by foodfan** [Slion/Fulguris#452]
"Incognito" doesn't work. If you're logged into a site like Twitter in regular mode, you continue to be logged in on incognito. Besides cookies, what other privacy details are leaking between the two modes? Needs fixing.

**Comment by Slion** [comment]
So true. Should be renamed as private and yes it needs improving in many ways I'm sure. However I just tried going on a website I was logged in to in normal mode and I was not logged in thenas expected. Was Android 11. Could you specify your Android version, WebView version and device?

**Comment by foodfan** [comment]
> So true. Should be renamed as private and yes it needs improving in many ways I'm sure. However I just tried going on a website I was logged in to in normal mode and I was not logged in then as expected. Was Android 11. Could you specify your Android version, WebView version and device?

I'm on Android 8 on a Galaxy S9+. Twitter is specifically where I noticed it. Then stopped using incognito.

**Comment by Slion** [comment]
> I'm on Android 8 on a Galaxy S9+. Twitter is specifically where I noticed it. Then stopped using incognito.

I tried it with Twitter and there too it works as expected on my device. I could try it on Android 7, I don't think I have any Android 8 devices I think.

**Comment by Helium314** [comment]
Works as intended for me, Android 9 + WebView 108.

**Comment by Slion** [comment]
Can't reproduce on Samsung Galaxy S7 Edge running Android 8. Unless we have more information there is nothing we can do here. I suggest you make sure you are running an up do date WebView version.
