### ISSUE TITLE
wikipedia mobile & desktop layouts are wrong?

### ISSUE THREAD

**Issue by jindamvani** [Slion/Fulguris#458]
@Slion 
* version 1.8.23 fdroid
str:
* wikipedia.org
* click english
* the layout of the website is odd, see there is gap on right & left side
* screenshot _mobile
* 
![mobile](https://user-images.githubusercontent.com/131695520/236121708-98ed7ad8-a900-4d28-a077-31e7e28b51d6.png)
*now click **desktop** at bottom of en.m.wikipedia.org
* the layout of the website is odd
* screenshot _desktop
* 
![desktop](https://user-images.githubusercontent.com/131695520/236121935-fd0c5192-2330-44d8-a6b2-b871adaeeaa4.png)

**Comment by Slion** [comment]
Looks good to me. Actually you are lucky it gives you the proper sidebar in desktop mode on some of my devices that ain't  working for some reason.

**Comment by jindamvani** [comment]
@Slion 
>Actually you are lucky it gives you the proper sidebar in desktop mode on some of my devices that ain't working for some reason.

* Perhaps you are using default 2022 vector skin.
* I am using vector legacy

**Comment by Slion** [comment]
I did not know they had skin. That would make sense then. Though you need to login to change the skin apparently.
Either way I don't think there is anything wrong there so I'm going to close that ticket if you are happy with that.
For desktop mode you can adjust the width from the Look & Feel settings for Portrait or Landscape.

**Comment by Slion** [comment]
I'm pretty sure that's how it is supposed to work.

**Comment by GameOverFlowChart** [comment]
I don't see anything wrong, hamburger buttons are for mobile, and sidebars are for desktop, that's how it makes sense because of the different screen sizes.

**Comment by Slion** [comment]
Closing as works for me then.
