### ISSUE TITLE
On some pages, you can't go back and it becomes refreshed

### ISSUE THREAD

**Issue by chwt163** [Slion/Fulguris#459]
For example, these pages:
https://www.mydrivers.com/
https://www.ithome.com/
Once these two URLs are open, you can't go back unless you quickly click back twice.
The experience is really bad, I hope Fulguris can improve.

**Comment by Slion** [comment]
Duplicate of #414

**Comment by chwt163** [comment]
The Einkbro browser solves this problem, can developers refer to it?
https://github.com/plateaukao/einkbro
