### ISSUE TITLE
Dark mode is not working properly

### ISSUE THREAD

**Issue by Justauser0** [Slion/Fulguris#462]
Without darkmode
![Screenshot_20230601-154900_1](https://github.com/Slion/Fulguris/assets/135147872/666c1590-e7dc-4dd5-9ad2-480c6691cbc8)

Dark mode enabled

![Screenshot_20230601-154914_1_1](https://github.com/Slion/Fulguris/assets/135147872/de113c44-a22c-4d54-8aa0-b95ce4eee8e6)

**Comment by Justauser0** [comment]
Any update

**Comment by Slion** [comment]
Cannot reproduce that issue. Which device, OS and WebView version are you using?

**Comment by Justauser0** [comment]
> Cannot reproduce that issue. Which device, OS and WebView version are you using?

Lenovo Tab 3 7plus, Android 6

**Comment by Slion** [comment]
Go to Settings > About > WebView then long press on WebView package to copy the info and past it here. It should looks like;
com.google.android.webview (114.0.5735.130/573513033)

Then again your device and software is about 10 years old. You are likely using an outdated WebView that does not do much smart with dark mode. It simply inverts the colours. So if you have dark page and turn on dark mode you get a light page. Just don't turn on dark mode for dark pages or find a way to update your software.

**Comment by Justauser0** [comment]
> Go to Settings > About > WebView then long press on WebView package to copy the info and past it here. It should looks like; com.google.android.webview (114.0.5735.130/573513033)
> 
> Then again your device and software is about 10 years old. You are likely using an outdated WebView that does not do much smart with dark mode. It simply inverts the colours. So if you have dark page and turn on dark mode you get a light page. Just don't turn on dark mode for dark pages or find a way to update your software.

![Screenshot_20230625-170002_1](https://github.com/Slion/Fulguris/assets/135147872/1990308c-a887-41ad-ba25-3cac215f1df2)

**Comment by Slion** [comment]
Your WebView is just 64 major version behind the current one which is v114. While I'm all for supporting older devices it does not make sense to spend much time on it.

**Comment by Slion** [comment]
I was just looking into that code and your WebView does not support dark mode so we just invert the colours instead. That's what you were seeing. For dark pages just don't for dark mode and you will be fine.
