### ISSUE TITLE
Promoting my fork of i2p lib

### ISSUE THREAD

**Issue by hmtheboy154** [Slion/Fulguris#471]
Hi, a while ago I made this fork of `i2p.android.base` in which I build new libjbigi with NDK r25c  & GMP 6.2.1
https://github.com/hmtheboy154/i2p.android.base

I build them not only for arm/arm64 but also x86/x86_64 too because i want x86/x86_64 support on Fulguris. I've tried these on a fork of Fulguris and it's working. 

Also here is my `i2p.i2p` fork with the edited script to compile
https://github.com/hmtheboy154/i2p.i2p

**Comment by Slion** [comment]
It does look like x86 is disabled in Fulguris. Not sure why that is. I'll look into it.

Could not find your Fulguris fork.
Is there anything else that we can do for you on that ticket?

**Comment by hmtheboy154** [comment]
> Could not find your Fulguris fork.
I'm using this fork 
https://github.com/nift4/Jellyfish

x86/x86_64 just being added here
https://github.com/nift4/Jellyfish/commit/f260999d3e0d983fec3aeedc559e549bbe3c1ce3#diff-51a0b488f963eb0be6c6599bf5df497313877cf5bdff3950807373912ac1cdc9R117

> Is there anything else that we could do for you related to that ticket?

nope, that's all, I just want the app to be supported universally

**Comment by hmtheboy154** [comment]
> It does look like x86 is disabled in Fulguris. Not sure why that is. I'll look into it.

I think that it's because back then `libjbigi` only have arm and arm64 version. So maybe you decided to build it arm only

**Comment by Slion** [comment]
That should add x86 support:
https://github.com/Slion/Fulguris/commit/0de102d1eeb54adfb88407fe67cf4f3b9fb92d71

**Comment by Slion** [comment]
> > It does look like x86 is disabled in Fulguris. Not sure why that is. I'll look into it.
> 
> I think that it's because back then `libjbigi` only have arm and arm64 version. So maybe you decided to build it arm only

I have no idea what `libjbigi` does so that must have been back in the time of Lightning under @anthonycr.
Does Fulguris have a dependency on that lib?

**Comment by hmtheboy154** [comment]
> > > It does look like x86 is disabled in Fulguris. Not sure why that is. I'll look into it.
> > 
> > 
> > I think that it's because back then `libjbigi` only have arm and arm64 version. So maybe you decided to build it arm only
> 
> I have no idea what `libjbigi` does so that must have been back in the time of Lightning under @anthonycr. Does Fulguris have a dependency on that lib?

yes, if you check `lib` in the apk
