### ISSUE TITLE
Import Export bookmarks not working

### ISSUE THREAD

**Issue by Jeb187** [Slion/Fulguris#490]
# Description
Tapping Import or Export bookmarks does nothing. Permission to access storage is not asked and not available in App Info. 

# Environment
 - Device: Pixel 6a
 - OS: Stock Android
 - Version: 1.8.28

![Screenshot_20230706-182435](https://github.com/Slion/Fulguris/assets/54668471/f156f006-555e-4c9e-8943-2df949fd4fa0)

**Comment by Slion** [comment]
Thanks for reporting this. Is it Android 13?

**Comment by Jeb187** [comment]
Yes, Android 13.

**Comment by Slion** [comment]
Export works on Android 10. File permission is asked when you enter the Backup settings.

**Comment by Jeb187** [comment]
Downgrading Android is not an option for me. 🙂

With Android 13, I'm not asked by Fulguris to grant permission, and I can't even grant it in settings "App Info" , because this option is simply not there. 

Am 13. Juli 2023 08:05:37 MESZ schrieb "Stéphane Lenclud" ***@***.***>:

**Comment by Slion** [comment]
I was merely collecting facts to help investigate the issue. Not suggesting you should downgrade 😁

**Comment by Slion** [comment]
Should be fixed in v1.8.29. Thanks for reporting that issue.

**Comment by Jeb187** [comment]
Yes, it is. Thank you!🙂
