### ISSUE TITLE
Pdf files do not open/download

### ISSUE THREAD

**Issue by manuscule** [Slion/Fulguris#495]
# Description
Whenever I try to open a pdf file from a link in Fulguris, nothing happens. When I try to open the sane link in a new tab, the tab opens and closes immediately, nothing else happens.

Please note that I'm not a developer and have no debugging skills. As a workaround, I copy the link to open it with the standard browser....

# Environment
 - Device: Fairphone 3
 - OS: Android 13, LineageOS 20-20230626-NIGHTLY-FP3
 - Version: net.slions.fulguris.full.fdroid version 1.8.28

# To reproduce
Steps to reproduce the behaviour:
1. Go to any page with a link to a PDF file
2. Click on the link to a PDF file
3. Nothing happens
4. Long click on the same link an press open in a new tab
5. Tab opens and closes immediately

# Expected behaviour
The PDF should be displayed or at least downloaded

**Comment by Slion** [comment]
Could you provide links to reproduce the issue?

**Comment by manuscule** [comment]
https://dagrs.berkeley.edu/sites/default/files/2020-01/sample.pdf

**Comment by manuscule** [comment]
I updated the bug description (tab opens only when I try to open the link in a new tab, if not, nothing at all happens)

**Comment by Slion** [comment]
Should be fixed in v1.8.29. Thanks for reporting that issue.

**Comment by manuscule** [comment]
Thank you very much, I'll try it out as soon as the version is available on f-droid.

**Comment by Slion** [comment]
I reckon it could take up to a week for the F-Droid variant to be released.

**Comment by manuscule** [comment]
Tested, approved and greatly appreciated!
