### ISSUE TITLE
Use userfriendly vocabulary instead of "Domain"

### ISSUE THREAD

**Issue by Cwpute** [Slion/Fulguris#517]
*New issue to continue the discussion started in #514 regarding specific aspects of it.*

**Summary of my original thoughts:**
When people think of different pages scattered across and spannig the same domain, most will refer to that collection of pages as a "Website" rather than a "Domain". While this may not be an entirely accurate word, it's definitely the most used out there, to my knowledge. So when searching for options to modify how that collection of pages is presented, i'd expect people to understand it better if they were presented with a section called 'Options for this Website' or something like that, instead of 'Domain'.
On another note, maybe the intent when creating the 'Web page' section was for it to later become the domain options section, as it serves a similar purpose with its quick settings regarding reader mode, dark mode etc… but with this new feature, i feel this section's name ups the confusion even more.

**Comment by Slion** [comment]
In Chrome they call it _Site settings_. All lot of the stuff on our _Web page_ menu is in fact specific to the tab.
I'm going to stick with _Domain settings_ for now but your feedback is very welcome. It could still be renamed at some point. Though I'm of the opinion we should stick with an accurate vocabulary rather the dumbing it down.
