### ISSUE TITLE
keyboard overlapping on libera gamja

### ISSUE THREAD

**Issue by jindam-vani** [Slion/Fulguris#525]
# Description
unable to view what i am typing on gamja libera chat website

# Environment
 - Device: samsung j7 nxt
 - OS: Android 9
 - Version: 1.3.4 fdroid

# To reproduce
Steps to reproduce the behaviour:
1. Go to https://web.libera.chat/gamja/
2. Join any channel, ex.: termux
3. try to start type something to send message
4. See screenshots

# Expected behaviour
keyboard should not overlap input area

# Screenshots
* when i stopped typing, tapping back key on device
![gamja](https://github.com/Slion/Fulguris/assets/109575325/dbf61703-9118-4555-920f-cc7666846f4a)
* after start typing
![keyboard_overlapping](https://github.com/Slion/Fulguris/assets/109575325/1e945d41-9a96-470f-9a65-91352a667868)

# keyboards
* indic keyboard 3.5.1 [ fdroid ]
* hackers keyboard 1.41.4 [ fdroid ]
* samsung keyboard 3.3

**Comment by Slion** [comment]
Works fine on Android 10:

![Screenshot_20230807_065722_net.slions.fulguris.full.playstore.jpg](https://github.com/Slion/Fulguris/assets/6508892/84c8c913-d064-46d9-aacd-1a3001245adf)

I'll need to try it on Android 9.

**Comment by Slion** [comment]
I tried on it on Samsung Galaxy S7 edge which is Android 8 and it works fine there too. Could also be an issue with your WebView I guess.
