### ISSUE TITLE
Enhanced keyboard/mouse support

### ISSUE THREAD

**Issue by alexcg1** [Slion/Fulguris#530]
First up, thanks for creating the best browser I've used so far on Android! I'm currently trying to convert my tablet to a super compact laptop (well, the cloest equivalent) and there are a few quality of life improvements I can think of for users like me.

I'm happy to try diving into the code to try to contribute if that helps.

BTW, if it's easier for me to dump each of these suggestions into separate issues instead of just one big one like this, I'm happy to do so.

**Is your feature request related to a problem? Please describe.**
Keyboard and mouse actions are *somewhat* in line with how they would work on a desktop, but some are missing or inconsistent.

**Describe the solution you'd like**
- Middle mouse click on link could open new tab in background
- Middle click in tab bar opens new tab
- Up/down keys select autocomplete action when typing in address bar
- No lag on right-click (right now it acts like a long-press)

**Describe alternatives you've considered**
None really

**Additional context**
I'm using Bluetooth tablet keyboard and Microsoft bluetooth mouse. Often in Samsung DeX mode to give a more desktop-like experience (however, stuff above also applies in pure tablet mode)

**Comment by Slion** [comment]
High quality code contributions are most welcome. Yes please open specific issues.
Fulguris is probably still the most desktop friendly Android Web browser. That is if you can get over going through the configuration which is a bit fiddly I admit.

The plan was to have configurable keyboard and mouse actions, see #21. Probably not a good first contribution though as that would be quite some work.

Closing that ticket, please open specific ones for the features you want to contribute.
