### ISSUE TITLE
Support .dat extension like bromite

### ISSUE THREAD

**Issue by IGProd** [Slion/Fulguris#541]
Hi,
is there a way to support .dat file like bromite adblock filter 
https://www.bromite.org/filters/filters.dat

Thx

**Comment by Slion** [comment]
Looking at the [docs](https://www.bromite.org/custom-filters) it seems those `dat` files are generated from various plain text filter files. It has no benefits other than possible faster loading time.

I don't see this happening unless a brave developer thinks it is a must have feature for some reason. I'll close it for now.

@Helium314 Any thoughts on that?

**Comment by IGProd** [comment]
> I don't see the point in parsing files that are created from lists that can already be used.
> 
> Is the Bromite filter.dat actually being updated, since Bromite seems unmaintained? Or is there an alternative source for such files?

i dont know if .dat is supported by fulguris 
this is live and update dat 
https://github.com/xarantolus/filtrite
the reason that i asked because the dat file support cosmetics filter,statics and dynamics ads

**Comment by Slion** [comment]
That dat thingy is not needed for that. Currently Fulguris does not support DOM manipulation to block content. Only resource URL content are blocked I believe.
