### ISSUE TITLE
Every website pop up with "Third Party App" question

### ISSUE THREAD

**Issue by SpaceOctopus** [Slion/Fulguris#542]
# Description
Every time I go to a new page - no matter where it is, a pop-up from the app shows, saying there is a "Third party app available" and asks if I want to launch the application associated with the website - there is none.

# Environment
 - Device: Oneplus 3
 - OS: Android 10
 - Version: 3.18.140

# To reproduce
Steps to reproduce the behaviour:
1. Go to ' any page'
2. Click on 'a link'

# Expected behaviour
Normal browsing - no error

# Screenshots
[Screenshot 1 ](https://i.imgur.com/bmWjdg8.jpg) 
[Screenshot 2](https://i.imgur.com/9fX4do1.jpg)

**Comment by Slion** [comment]
Menu / Settings / Domains / Default / Launch app / No

**Comment by 6801318d8d** [comment]
> Menu / Settings / Domains / Default / Launch app / No

Can we have it for top level domains (wikipedia.org, instead of en.wikipedia.org)?

**Comment by Slion** [comment]
> > Menu / Settings / Domains / Default / Launch app / No
> 
> Can we have it for top level domains (wikipedia.org, instead of en.wikipedia.org)?

Yes that works too. Go to your Wikipedia page then Menu / Options / Domain / Parent / Launch app / No

**Comment by Slion** [comment]
Related to #612

The screenshots above are refering to:
- https://www.countrycrock.com
- https://www.rhymezone.com
