### ISSUE TITLE
Allow bookmarks among search suggestions

### ISSUE THREAD

**Issue by Cwpute** [Slion/Fulguris#543]
**Is your feature request related to a problem? Please describe.**
Having quite a few favourites, i find myself using them very often. Browsing through the favourites list can be pretty long though, also often i remember part of the link but not necessarily the page name which can be tricky vhen searching for them.

**Describe the solution you'd like**
Being able to search through favourites from the search/link bar at the bottom, and have them appear as suggestions, would solve my issue.

**Additional context**
A similar feature was requested for tabs in sessions: https://github.com/Slion/Fulguris/issues/37

**Comment by Slion** [comment]
That should already be working. Just tested it both URL and title match are working.

**Comment by Cwpute** [comment]
yeah it… does work. sorry i dont know what happened.

**Comment by Cwpute** [comment]
With some more testing i think it's because i am only allowing 2 search results to appear, since when i switch to 6 search results instead, the bookmarked tab does appear in the suggestions. It seems to be specific to for often-browsed websites like facebook and github in my case, but not for others.
