### ISSUE TITLE
Opt-out check for updates

### ISSUE THREAD

**Issue by IzK666** [Slion/Fulguris#546]
Can you implement an easier way to disable update checks?
As you know (you've made a comment in the code), the popup is really disturbing and I'm not interested on being notified everytime I open the app just to know that you updated some translations (which many people will like, of course, but not me).

BTW: Although my critisism about this missing and IMHO important feature, I like your browser for it's simplicity, and all the features it offers ;)

**Comment by Slion** [comment]
Duplicate of #88
