### ISSUE TITLE
Javascript enable/disable toggle

### ISSUE THREAD

**Issue by mjray** [Slion/Fulguris#547]
**Is your feature request related to a problem? Please describe.**
I sometimes want to enable javascript for a site for a few pages, to accomplish something which the badly-designed site does not allow noscript users to do.

**Describe the solution you'd like**
I'd like a menu checkbox for "Enable javascript" similar to "Content control".

**Describe alternatives you've considered**
I currently use another browser for such sites but that is cumbersome and the other browser doesn't seem as good as Fulguris. I'm building up Fulguris's exception list, but it's slow to add sites to the scripting exception list and that doesn't help with sites where I only need scripting for short periods of a few pages.

Thanks for considering this feature request.

**Comment by Slion** [comment]
The plan is to move JavaScript to the domain settings. The exception list would then be removed. Page level toggle will definitely be considered too.

**Comment by Slion** [comment]
@mjray Currently publishing v1.9.11 where JavaScript option has moved to domain settings. Did not implement page toggle though. Just let me know if that is good enough for you.

**Comment by Slion** [comment]
Fixed in 02d5c22 as we moved JavaScript to domain settings.

**Comment by mjray** [comment]
> Currently publishing v1.9.11 where JavaScript option has moved to domain settings. Did not implement page toggle though. Just let me know if that is good enough for you.

Yes, that's now fed through to my app store, has been used for a few weeks and it works well enough. It's still over ten taps for a one-off visit (like a survey form), but it's much better than copy-pasting addresses into Settings. Thanks.
