### ISSUE TITLE
Press and hold menu on links doesn't work most of the time

### ISSUE THREAD

**Issue by MikaelaMuller** [Slion/Fulguris#549]
# Description
Long press menu doesn't appear most of the time

# Environment
 - Device: [Samsung galaxy Tab A gtexslte (spreadtrum variant)
 - OS: [Android 7.1.2 LineageOS]
 - Version: [1.9.11playstore , 1.9.8fdroid]

# To reproduce
Steps to reproduce the behaviour:
1. Go to google or any website.
2. Press and hold on any link

# Expected behaviour
The long press menu should appear allowing me to open new tabs and other goodies.

# Screenshots
![Screenshot](https://cdn.discordapp.com/attachments/828559559680983050/1151497863554142278/8mb.video-kTU-B99XWPZa.mp4)

# Additional contexts
Webview Version: com.google.android.webview
v116.0.5845.163

**Comment by Slion** [comment]
This is a WebView issue caused by WebViewImageDrag as [explained there](https://discord.com/channels/828559272752840713/828559559680983050/1151646963259940966). We should really report that to the Chrome project.
