### ISSUE TITLE
Faster access to web page actions

### ISSUE THREAD

**Issue by Lavmint** [Slion/Fulguris#561]
**Is your feature request related to a problem? Please describe.**
Page related context menu is used more often than app-related. Switching context menu every time you need to do something with a page is a bad UX. I was not able to find "search in page" the first time I needed it

**Describe the solution you'd like**
Option1: add an extra button next to the search bar to separate web-page related and app-related context menus. 

**Describe alternatives you've considered**
Option2: use the same button, but use 2 different gestures, e.g. a long press and an ordinary tap
Option3: keep one button, but let user prioritize which menu is presented by default
Option4: scroll view with section separators like in [DuckDuckGo](https://github.com/duckduckgo/Android)

**Additional context**
issued flow: lightning button -> Web page context menu -> Main context menu

**Comment by Slion** [comment]
In the next release you should be able to open the web page menu directly by doing a swipe on the menu button instead of a tap.
Would that be OK for you?

**Comment by Lavmint** [comment]
> In the next release you should be able to open the web page menu directly by doing a swipe on the menu button instead of a tap.
> Would that be OK for you?

Area of the menu button is very small, it's a bad UX to make swipes in a small area like this. Btw, I just discovered that a long press is already doing something, some kind of a not very useful overlayer with 3 buttons

**Comment by Slion** [comment]
> Area of the menu button is very small, it's a bad UX to make swipes in a small area like this.

It's a vertical swipe, up or down, depending on where you put your toolbar, it is not contrained to the button area.

**Comment by Slion** [comment]
>  Btw, I just discovered that a long press is already doing something, some kind of a not very useful overlay with 3 buttons

I quite like it 😁 I call it touch tab switcher. You can use it just like you use Ctrl + Tab shortcut on a keyboard. The web page menu is on the menu button however not the tab button.

**Comment by Slion** [comment]
You can now acces the web page menu by doing vertical swipe or double tap on the menu button.
