### ISSUE TITLE
Empty tabs  when disabling tab change animations 

### ISSUE THREAD

**Issue by NektoNektovich** [Slion/Fulguris#565]
Android 6.0, system webview 103
I installed version 1.9.14 from the official website - it worked fine. I updated today to version 1.9.16 and the browser shows nothing :(

![Screenshot_20231010-173418](https://github.com/Slion/Fulguris/assets/53621368/76d26871-c723-4ca7-9e1e-f0aee5b562ba)

**Comment by Slion** [comment]
Try reset the app data or you could just uninstall and reinstall. Another guy had the same issue and that fixed it for him. Not sure why that is.

**Comment by YOEL-44** [comment]
This bug only happens when you disable the tab changing animation, I guess not many people does it.

**Comment by NektoNektovich** [comment]
> This bug only happens when you disable the tab changing animation, I guess not many people does it.

I always turn off all animations. I can't stand them!

**Comment by Slion** [comment]
> This bug only happens when you disable the tab changing animation, I guess not many people does it.

Nice one, I'll looks into it now that I can reproduce it. Do you know if this is something new in 1.9.15 or 1.9.16?
It used to work fine right?

**Comment by NektoNektovich** [comment]
> Nice one, I'll looks into it now that I can reproduce it. Do you know if this is something new in 1.9.15 or 1.9.16?
> It used to work fine right?

thank you, I hope that it will be possible to turn off the animations again :) everything seems to be working and working, I like the domain settings! but the integration of third-party download managers and manual selection of advertising banners to add to advertising filters is a little lacking :)

**Comment by NektoNektovich** [comment]
> So it was still working on 1.9.14. I'm pretty sure that regression was introduced in 1.9.15. Thanks guys for the help here. I'll look into it.

I didn’t update to 1.9.15, I missed it and after 1.9.14 I immediately installed 1.9.16

**Comment by Slion** [comment]
> I always turn off all animations. I can't stand them!

They are probably not very smooth on Android 6 hardware. Personally I love them. That's my favorite feature after Sessions. Though I do understand why some people may not like them. That is why we have the settings options to disable them 😁

**Comment by Slion** [comment]
v1.9.17 is available for download

**Comment by NektoNektovich** [comment]
> v1.9.17 is available for download

Thanks a lot! 👍🤩🤗
