### ISSUE TITLE
Check file access permissions for download

### ISSUE THREAD

**Issue by lifeincage** [Slion/Fulguris#573]
Here is your feature request translated and formatted as a GitHub issue:

**Is your feature request related to a problem? Please describe.**
This browser requires the user to grant file and media read/write permissions when downloading files. However, the import and export functions for backup settings do not require authorization and seem to directly use the system file picker. Why can't the system file picker be used uniformly? Many users are unwilling to open file read/write permissions to third party apps.

**Describe the solution you'd like**  
Use the system file picker uniformly across all file operations like downloading and importing/exporting backup settings. This avoids requiring extensive file permissions from users.
Or just write download file directly into Download folder, like some browsers did.

**Describe alternatives you've considered**
The only alternative seems to be keeping the current mixed permission model of requiring permissions for downloads but using the system file picker for backups.

**Additional context**  
Requiring fewer permissions from users and using the system file picker could increase user trust/satisfaction and avoid support issues related to file permissions.

**Comment by Slion** [comment]
Your issue is about the fact that file download requests permissions?

I wonder if this is the case because one could select a download folder which needs those permissions.

**Comment by lifeincage** [comment]
Sorry, I'm not too familiar with Android development, but I have tried many different browsers in F-Droid, such as Fennec Fdroid/Mull/Mulch/DuckDuckGo, etc. Many of these browsers do not require extra file read/write permission when downloading files, and they downloading files to the Download directory by default. There's also a browser called Monocles that pops up a window to choose the save path. Or maybe they're using a newer API?

In addition, Fulguris is my favorite browser on Lineageos, so I would like to humbly offer a suggestion.

**Comment by lifeincage** [comment]
Solved. After Android version uodated to 13, it doesn't require additional permission.
