### ISSUE TITLE
Content control breaks Framateam.org

### ISSUE THREAD

**Issue by Cwpute** [Slion/Fulguris#581]
# Description
Framateam is a mattermost instance accessible from the web-browser. When used with Content Control, the chat window is pushed down and most buttons are inaccessible.
When CC is disabled, the page renders as expected.

# Environment
 - Device: Nokia TA-1157
 - OS: Android 11
 - Version: 1.9.17

# To reproduce
Steps to reproduce the behaviour:
1. Go to Framateam.org
2. Connect to your account

# Expected behaviour
The chat window should render entirely with Content Control on.

# Additional context
I've read in #293 that uBlock's Annoyances list wasn't supported… i have a feeling this might come from here.

**Comment by Slion** [comment]
Is this page working properly when using the same ad blocker definitions with another browser?

**Comment by Cwpute** [comment]
i don't know and i can't tell as i don.t have access to a reliable computer with a reliable internet connection right now :/

**Comment by Cwpute** [comment]
Wanting to test it on the computer, i saw there was an on-off button for Modifying filters, and the little blurb associated to it... it seems deactivating them for the mainframe seems to help.
So i guess this issue will remain stale unless a proper implementation of Modifying filters !
I'll mark it as not planned for now...
