### ISSUE TITLE
Move Tab(s) to another session

### ISSUE THREAD

**Issue by SIRSteiner** [Slion/Fulguris#582]
**Is your feature request related to a problem? Please describe.**
Fulguris opens external links always in the first session. Often I would save the tab at another session. I didn't find a way to move  tabs to another session.

**Describe the solution you'd like**
Swipe tab left to move tab (in tab view).

Thank you

**Comment by Slion** [comment]
https://slions.net/threads/how-to-move-tabs-between-sessions.72/

**Comment by SIRSteiner** [comment]
Thank you for your quick reply. Okay, it is a way but I think it is not very intuitive.

**Comment by Slion** [comment]
There is no plan to improve on that at the moment I'm afraid.
