### ISSUE TITLE
broken link on your GitHub page

### ISSUE THREAD

**Issue by cpo-ux** [Slion/Fulguris#588]
http://fulguris.slions.net/
doesn't work.

https://slions.net/
does work though.

![2023-12-23 13_03_30-Slion_Fulguris_ ⚡Web Browser](https://github.com/Slion/Fulguris/assets/59980654/fab5c022-d6c2-40d2-a5f8-3e8c2ad7da7d)

**Comment by Slion** [comment]
http://fulguris.slions.net/ works
https://fulguris.slions.net/ does not work

You probably tried to open that link using some app or browser that thought it could just replace http with https and expect it to work. That's a bug with the GitHub app I believe. Having said that I ought to make the https redirect work at some point.

**Comment by cpo-ux** [comment]
> http://fulguris.slions.net/ works https://fulguris.slions.net/ does not work
> 
> You probably tried to open that link using some app or browser that thought it could just replace http with https and expect it to work. That's a bug with the GitHub app I believe. Having said that I ought to make the https redirect work at some point.

Yes using Chrome Version 120.0.6099.130 on Windows 10.

**Comment by Slion** [comment]
> Yes using Chrome Version 120.0.6099.130 on Windows 10.

That's weird. I just tried with Edge and Vivaldi and it works fine cause the link provided is http not https. It's either a bug with GitHub sending you the wrong link or with Chrome just deciding to go https for whatever reason. Feel free to report that bug to Chrome and/or GitHub.
