### ISSUE TITLE
[BUG]: Snackbar has inverted colors to the app's theme

### ISSUE THREAD

**Issue by piotr-marendowski** [Slion/Fulguris#590]
# Description
When the theme is set to `dark` or `black` then snackbar appearing at the bottom of the screen is white, but when the theme is set to `light` then snackbar is dark.

# Environment
 - Device: Huawei WAS-LX1
 - OS: Android 11
 - Version: 1.9.17 from F-Droid

# To reproduce
Steps to reproduce the behaviour:
1. Open a tab
2. Close a tab
3. See a snackbar appear at the bottom of the screen

# Expected behaviour
Snackbar should follow app's theme.

# Screenshots

<details>

<summary>Dark/Black theme</summary>

![image](https://github.com/Slion/Fulguris/assets/37738748/5afca5d2-34dd-4e49-9f58-2a309d44634c)

</details>

<details>

<summary>Light theme</summary>

![image](https://github.com/Slion/Fulguris/assets/37738748/a1e4013b-5303-4541-9373-c21e0668dcac)

</details>

**Comment by Slion** [comment]
This is how it is by default in material design. It is so that the snackbar contrasts with the UI underneath. Though many applications are overriding it I think. Currently not planning to change it. One day maybe, I which case we should reopen that issue.
