### ISSUE TITLE
Query third party sites

### ISSUE THREAD

**Issue by Yuri-VK** [Slion/Fulguris#606]
The browser user had a problem and here I will quote what bothered him.
"Can anyone tell me why Fulguris “climbs” on the resources linkmaker.itunes.apple.com and play.google.com, respectively, on apple.com and google.com too, especially without the Internet? For JavaScript to work, perhaps ?" This is his quote and he wants to hear a possible answer from the developer.

**Comment by Slion** [comment]
It should not do that unless the WebView being use is doing it for some reason, or it could be that Firebase is doing that. You can turn it off from the Privacy settings or just use the F-droid variant.

**Comment by Slion** [comment]
Not enough information to investigate that further.
