### ISSUE TITLE
Improve third-party app launch behaviour

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#612]
[Test URLs](https://slions.net/threads/browser-test-urls.115/)
[Android Intents with Chorme](https://developer.chrome.com/docs/android/intents)

From @ZhymabekRoman

- Basic test: https://t.me/durov, https://api.whatsapp.com/send?phone=91
- Testing `browser_fallback_url`: open random Reddit page and press "Use App" button in top of the page. [Example](https://www.reddit.com/r/Damnthatsinteresting/comments/1bj2ff2/no_idea_how_she_was_able_to_keep_a_straight_face/?xpromo_edp=enabled). If domain app settings set to "Yes" it should open Reddit, either if Reddit is not installed it's should open search page in Play Market with Reddit package name. If domain app settings set to "Ask", after pressing "No" in the message box, it's should trigger `browser_fallback_url` page. `browser_fallback_url` is just a Play Market page of the Reddit application.
- https://play.google.com/store/apps/details?id=com.reddit.frontpage - If domain app settings set to "Ask" navigating Play Market page shouldn't trigger intent execution without user promt. After pressing "See in Play store" it's should open Play Market.

See #610.

**Comment by Slion** [comment]
@ZhymabekRoman If I click on https://t.me/durov and I don't have telegram install and third-party app launch is set to ask it still asks even though there is not app to launch.

**Comment by ZhymabekRoman** [comment]
> If I click on [t.me/durov](https://t.me/durov) and I don't have telegram installed and third-party app launch is set to ask it still asks even though there is no app to launch.

Hmmm, if Telegram isn't installed it should open the Play Market page of the Telegram application, or is there like something else that should happen? I thought it's like normal behavior. If there is no `browser_fallback_url` params, it's an only way to handle that condition. Or maybe we need to ask a user like, "You don't have an application installed that can handle the `tg:` protocol. Open Play Market to search for applications that can handle the action?"

We also need to make an options box for custom intent execution schemes, as the Firefox desktop does. Useful if there are multiple applications available to handle the scheme or intent action.

![image](https://github.com/Slion/Fulguris/assets/61125068/b0efd093-92f6-4c61-9ee8-6fdccdbf64f8)

**Comment by Slion** [comment]
> Hmmm, if Telegram isn't installed it should open the Play Market page of the Telegram application

That's what I figured from your original description but it does not do that on the device I tested. Also with reddit if I say launch the  app then no nothing happens, which is fine I guess.

If there is no app to handle the intent I guess we should not ask in the first place and just show the Telegram page in this case.

**Comment by Slion** [comment]
I converted that Java file to Kotlin. Hopefuly I did not break anything in the process.

**Comment by ZhymabekRoman** [comment]
> That's what I figured from your original description but it does not do that on the device I tested. 

I don't have a device without a Telegram installed, so I can't test it.

**Comment by Slion** [comment]
Fair enough, don't worry I'll look into it.

**Comment by Slion** [comment]
Why did you have to explicitly handle `mailto`, `tel` and `intent` schemes? I'm prety sure they were working before.

**Comment by ZhymabekRoman** [comment]
> I'm guessing that did the trick to fix

Yeap

**Comment by ZhymabekRoman** [comment]
I think I can help with debugging. I just disable telegram for a while, without deleting.

**Comment by Slion** [comment]
Up to you but I already have changes in the pipeline and we don't want to have conflicts 😁
If you want to chat feel free to join Discord.

**Comment by ZhymabekRoman** [comment]
> Up to you but I already have changes in the pipeline and we don't want to have conflicts

Haha, yeah of course. I will fork repo with latest changes.

**Comment by Slion** [comment]
@ZhymabekRoman I'm done with this for now. Feel free to test the latest changes. I'm about to do a new release.

**Comment by ZhymabekRoman** [comment]
@Slion Great work! Everything works like a charm.

**Comment by Slion** [comment]
Did more changes and released them already.
