### ISSUE TITLE
Crash while playing YouTube video

### ISSUE THREAD

**Issue by Unacceptium** [Slion/Fulguris#641]
# Description
i am watching a YT video when the video itself started to lag with random delays between and the sound started to flicker
app shut down instantly and dropped to home screen.
after startup again the pages i opened is gone. the app got uncommonly long time to start too.
# Environment
 - Device: Honor RKY-LX1 (chineese-made smartphone)
 - OS:Android 12 Magic UI6
# To reproduce
it happened just now and never did before (i use fulguris at least for half year now) but you just watch a video on Youtube and if you're (un)lucky it happens i think
# Expected behaviour
don't crash
# Additional context
crashlog. hope it helps.
[IndexOutOfBoundsException_1716139466412.txt](https://github.com/Slion/Fulguris/files/15370225/IndexOutOfBoundsException_1716139466412.txt)

i would like to mark that the browser did reload pages a lot with the snackbar message "render process has crashed" but it never shut down the app.
# Edit
app version: 1.9.27
made issue readable

**Comment by Slion** [comment]
>  would like to mark that the browser did reload pages a lot with the snackbar message "render process has crashed" but it never shut down the app.

The ad blocker can cause such issues. Try disable content control on the website where you encounter that issue and see if it helps.

**Comment by Slion** [comment]
I doubt the crash log provided correspond to the crash you are describing. Can you check if the time stamp on the file matches your crash?

Your crash sounds like a native driver layer crash and more often than not there is nothing that can be done at the app level to help with that. We probably won't generate crash logs for it either.

Where you using a mouse with that device at some point? The crash log you provided can happen when using mouse.

**Comment by Unacceptium** [comment]
no i'm using the normal touchscreen. and this is the only crash log Fulguris made until today so this should be the one (file date is 2 mins after the crash) but if the video player is a systemwide player and not integr. to fulguris its logical these logs shouldn't have a different software's crash. if thats the case we could close this issue i think.
