### ISSUE TITLE
Missing dependency and facing error while building

### ISSUE THREAD

**Issue by maya-56** [Slion/Fulguris#650]
In using Fulguris long time but  recently Im facing below error. Looks some dependency removed. Can you any one please help me

implementation 'com.anthonycr.grant:permissions:1.1.2'
final def mezzanineVersion = '1.1.1'
implementation "com.anthonycr.mezzanine:mezzanine:$mezzanineVersion"
kapt "com.anthonycr.mezzanine:mezzanine-compiler:$mezzanineVersion"
implementation "info.guardianproject.netcipher:netcipher-webkit:2.0.0-alpha1"

Could not find permissions-1.1.2.aar (com.anthonycr.grant:permissions:1.1.2).
        Searched in the following locations:
            https://plugins.gradle.org/m2/com/anthonycr/grant/permissions/1.1.2/permissions-1.1.2.aar
            
Could not find mezzanine-1.1.1.jar (com.anthonycr.mezzanine:mezzanine:1.1.1).
        Searched in the following locations:
            https://plugins.gradle.org/m2/com/anthonycr/mezzanine/mezzanine/1.1.1/mezzanine-1.1.1.jar

Could not find netcipher-webkit-2.0.0-alpha1.jar (info.guardianproject.netcipher:netcipher-webkit:2.0.0-alpha1).
        Searched in the following locations:
            https://plugins.gradle.org/m2/info/guardianproject/netcipher/netcipher-webkit/2.0.0-alpha1/netcipher-webkit-2.0.0-alpha1.jar

**Comment by maya-56** [comment]
Any one help here ???

**Comment by Slion** [comment]
It sucks if those guys are gone it will take some effort to sort it out.

**Comment by maya-56** [comment]
I have apk. Is there any way to extract from it.
[Uploading Fulguris1.zip…]()

**Comment by Slion** [comment]
Good thinking but I think someone should report that issues to the guys at gradle.org really.

**Comment by maya-56** [comment]
Thanks you I have fixed all issues by adding those dependency sources as a
modules in current code. It tooks some time but finally it is working fine

**Comment by Justlike48** [comment]
same issue found, please request to resolve the issue.

**Comment by sampatsharma143** [comment]
i was able to solve it by changing few things , 
I created a new library of grant permission and added the java files of original code and than added it into build.gradle 
        implementation(project(":grant"))
and in settings.gradle 
       include ':grant'
i had to remove the "info.guardianproject.netcipher:netcipher-webkit:2.0.0-alpha1"
as i don't need this , but we can also add this library as offline library, 

replaced the previous mezzanine dependancy lines with these new 
       implementation 'com.github.anthonycr.Mezzanine:mezzanine:v1.1.1'
       kapt "com.github.anthonycr.Mezzanine:mezzanine-compiler:$mezzanineVersion"

added         maven { url 'https://www.jitpack.io' }
in build.gradle ( Project Level )

**Comment by gigoplast** [comment]
> I have apk. Is there any way to extract from it. Uploading Fulguris1.zip…

Can u please refer the link note as github linker , exp:' www site com '.
github destroy links under their system : your link become like this Fulguris1.zip… ==" https://github.com/Slion/Fulguris/issues/650" . no way to retrieve your link
if there is a chance re.upload the zip .
APPRECIATE and Thanks by the way

**Comment by Slion** [comment]
So dependencies can't be found because JCenter was shutdown. Can we not just use a mirror as mentioned [there](https://stackoverflow.com/a/74284216/3969362) until we sort out each dependencies?

**Comment by Slion** [comment]
@sampatsharma143 Not sure how you got the mezzanine dependency to resolve.
I actually have the binaries for Permission, Netcipher and Mezzanine but I can't find the Mezzanine-Compiler.

Does anyone have the JAR for Mezzanine-Compiler v1.1.1? 
I can build Mezzanine which was updated earlier this year but then I get compilation error when using the resulting JAR to build Fulguris.

@maya-56 Any help with that would be great.

**Comment by Slion** [comment]
@sampatsharma143 Ok thanks, I got Mezzanine dependency working from JitPack.

```
    final def mezzanineVersion = '1.1.1'
    implementation "com.github.anthonycr.Mezzanine:mezzanine:$mezzanineVersion"
    kapt "com.github.anthonycr.Mezzanine:mezzanine-compiler:$mezzanineVersion"
```

**Comment by lwz-tech** [comment]
> i was able to solve it by changing few things , I created a new library of grant permission and added the java files of original code and than added it into build.gradle implementation(project(":grant")) and in settings.gradle include ':grant' i had to remove the "info.guardianproject.netcipher:netcipher-webkit:2.0.0-alpha1" as i don't need this , but we can also add this library as offline library,
> 
> replaced the previous mezzanine dependancy lines with these new implementation 'com.github.anthonycr.Mezzanine:mezzanine:v1.1.1' kapt "com.github.anthonycr.Mezzanine:mezzanine-compiler:$mezzanineVersion"
> 
> added maven { url 'https://www.jitpack.io' } in build.gradle ( Project Level )

hi brother, can you provide the "info.guardianproject.netcipher:netcipher-webkit:2.0.0-alpha1" offline files

**Comment by Slion** [comment]
https://github.com/Slion/Fulguris/blob/main/app/libs/netcipher-webkit-2.0.0-alpha1.jar

**Comment by lwz-tech** [comment]
> https://github.com/Slion/Fulguris/blob/main/app/libs/netcipher-webkit-2.0.0-alpha1.jar

thank you very much bro, I imported the offline jar package, this error has been fixed. You have com.anthonycr.progress:animated-progress:1.0  jar, my project. Com anthonycr. Progress: animated - progress: 1.0 this also can not find, and unable to download

**Comment by Slion** [comment]
It should have worked with the unmodified and clean tip of main branch. The CI builds worked anyway.

**Comment by lwz-tech** [comment]
> It should have worked with the unmodified and clean tip of main branch. The CI builds worked anyway.

I'm sorry that the project is clean and unchanged. I just modified the dependency and built it directly, but I still reported an error. The situation is as follows: Is there any place where I am not matched? Thank you
![1736252130838](https://github.com/user-attachments/assets/dbcb540d-af12-46ba-b21c-15f1ab43cc9a)

**Comment by Slion** [comment]
You are trying to build Lightning not Fulguris, good luck with that.

**Comment by swatiattri25** [comment]
> https://github.com/Slion/Fulguris/blob/main/app/libs/netcipher-webkit-2.0.0-alpha1.jar

@Slion This Jar is not able to resolve - `info.guardianproject.netcipher.proxy.OrbotHelper`. Am I missing something here?

**Comment by Slion** [comment]
Could be maybe there are other JARs missing.
