### ISSUE TITLE
Scrollbars don't scroll (can't be dragged)

### ISSUE THREAD

**Issue by pezcurrel** [Slion/Fulguris#653]
# Description
Even after setting the scrollbars to their maximum size and disabling their fading, they are not draggable, so one can't scroll the webpage with them.

# Environment
 - Device: Nokia TA-1535
 - OS: Android 12
 - Version: Fulguris v1.9.30

**Comment by Slion** [comment]
Duplicate of #497.
See: https://github.com/Slion/Fulguris/issues/497#issuecomment-1692765740
