### ISSUE TITLE
Add option to disable pull-to-refresh

### ISSUE THREAD

**Issue by UlyssesZh** [Slion/Fulguris#654]
**Is your feature request related to a problem? Please describe.**
The pull-to-refresh feature is sometimes undesired.

**Describe the solution you'd like**
Add a toggle in settings to optionally disable the pull-to-refresh feature.

**Describe alternatives you've considered**

**Additional context**

**Comment by Slion** [comment]
Go to Settings > Look & feel > Portrait or Landscape > Pull to refresh
