### ISSUE TITLE
Releasing to a void

### ISSUE THREAD

**Issue by ildar** [Slion/Fulguris#66]
I see this fork got released a few times already. But I don't see any binary apk anywhere. Who's testing it? ;-)
May I suggest?
1. add CI actions. Github can build automatically. Any user can pull at least a debug apk and quickly install it.
2. change app id and push to F-Droid.
3. do (1 and 2) or (1 or 2) ;-)

**Comment by Slion** [comment]
See:
https://slions.net/resources/fulguris.10/updates

You can download older releases from there:
https://slions.net/resources/fulguris.10/history

CI would be nice, have not gotten around it yet.

**Comment by Slion** [comment]
App ID is not the same as Lightning if that's what you worry about. You can have both Fulguris and Lightning installed at the same time.

**Comment by ildar** [comment]
Ah! sorry again. Missed that big Download button.
