### ISSUE TITLE
Build project

### ISSUE THREAD

**Issue by kovilevi98** [Slion/Fulguris#74]
I would like to build your project, inspect the code, and try to customize for my needs.
I have this error message : ` File google-sevices.json is missing `. I know it is for firebase.
Can you tell me what functions use it? And what should I do for building the project?

**Comment by Slion** [comment]
Try building the variant that I build I believe most other variants are broken at build or run time.
It's SlionsFullDownload I guess.

**Comment by kovilevi98** [comment]
Thanks for your answer the slionsFullDownloadRealse works well.
