### ISSUE TITLE
Theme special URLs

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#78]
- [x] Theme History page
- [x] Theme Google home page
- [ ] Theme Bookmarks home page

**Comment by jamal2362** [comment]
Theme Bookmark Site to current theme:
https://github.com/jamal2362/Styx/commit/a49a1f3c60888d433346331883f2005414c201a0

Little smaller Text Size in History Page:
https://github.com/jamal2362/Styx/commit/65d6ad22abcda36e95476933532463fbca843015

Search button now adapts to the current language:
https://github.com/jamal2362/Styx/commit/0284a7f6e08e69063e976c098554542aab262c9b

Fixed translated title for homepage:
https://github.com/jamal2362/Styx/commit/a1bb6cb75cfa58c588bdcba83b590c395488f454

Theme Homepage to current theme:
https://github.com/jamal2362/Styx/blob/0284a7f6e08e69063e976c098554542aab262c9b/app/src/main/html/homepage.html
