### ISSUE TITLE
What about backup and restore

### ISSUE THREAD

**Issue by ildar** [Slion/Fulguris#83]
This might be critical once you'll want to change app id

**Comment by Slion** [comment]
What would you backup?
- Settings
- Bookmarks
- Tabs

**Comment by Slion** [comment]
Why do you think I will want the change app id?
App id has already been changed from Lightning so you can install both at the same time.

**Comment by ildar** [comment]
Oh! sorry! Looking at old discussions I started to think you kept the
Lightning app id. sorry.
Then I know of no other issues that prevent Fulguris from entering F-Droid
repos. That implies build from source and full FOSS libraries set. If you
agree, I start the procedure (actually asking in RFP).

**Comment by Slion** [comment]
@ildar I see, so this is more about publishing on F-Droid than about backup and restore.
I've cretated issue #84 about publication on F-Droid. Please feel free to discuss there how you want to help with that. ATM I don't have CI or any sort of automated build system. I have no experience on publishing on F-Droid either.
Please do not publish it as it is on F-Droid as the app id would indeed need to be changed to allow parallel installations from other sources. Other things such as the app update check would also need to be disabled or changed.

You do know that Fulguris is available for download from [slions.net](https://slions.net/resources/fulguris.10/) right?

**Comment by ildar** [comment]
Yes. Actually app id change is painful for mere users and usually solved
with backup/restore. So with a separate app id (already) it becomes
low-priority.
BTW, I don't know why you want the parallel installations hassle. Many
developers are happy with a single app id )))
Thanks.

**Comment by Slion** [comment]
Close as backup and restore features will be handled on #123 
F-Droid publication issues are tracked on #84
