### ISSUE TITLE
Publishing on F-Droid

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#84]
A new flavour and app id should be created for publication on F-Droid.
Some features such as the version checker may need to be adapted for that flavour.

**Comment by ildar** [comment]
https://gitlab.com/fdroid/rfp/-/issues/1442

**Comment by ildar** [comment]
App ID doesn't have to be changed. Many apps live that way: published on
Play Store apk having developer's signature and published in F-Droid with
the same app ID with F-Droid's signature. Though there's a third way,
verified builds: https://verification.f-droid.org/
Flavors is a must thing if the app carries proprietary libs. Then FOSS
flavor would make apk pure and good for F-Droid. Otherwise optional.

**Comment by Slion** [comment]
> App ID doesn't have to be changed.

It will be changed please do not publish it with current app ID. I'll try to commit the required changes in the coming days.

For development and testing purposes having different app ID is so much easier. Moreover some features such as the version checker may need adjusting.

**Comment by ildar** [comment]
ok. https://gitlab.com/fdroid/rfp/-/issues/1442#note_391197126

**Comment by Slion** [comment]
This is now ready for publishing on F-Droid.
Build slions branch using slionsFullFdroidRelease variant.

**Comment by Slion** [comment]
Publication on F-Droid was denied because of dependencies against Firebase. A little more work would be needed then to be able to publish on F-Droid.

**Comment by Slion** [comment]
Too much pain too little gain. This is postponed indefinitely.

**Comment by mid-kid** [comment]
Is it really that hard to remove firebase, or is there more to this?

**Comment by Slion** [comment]
No it should not be and I don't think there is more to this. Except that I would need to manage three flavors and channels for each release instead of two. That could increase my workload by release.
Are you not happy with the download variant? You know you can disable firebase  from the privacy settings.

**Comment by Slion** [comment]
@IzzySoft what are we still missing here? Can we give this another go?

We said we would try it with the Unicode characters in fastlane. That could also be easily fixed though.
Then the build bot was getting confused with app id. This is potentially fixed by now as the original acr lightning flavour as been removed.
If you guys need to tags to trigger the build I can also create tags for you, just tell me what those tags should look like.

**Comment by Slion** [comment]
Looks at your [latest post](https://gitlab.com/fdroid/rfp/-/issues/1442#note_722168035) it looks like the build bot was picking up the app id that was commented out. That sounds like an easy fix.

**Comment by IzzySoft** [comment]
Looks like our maintainer-in-residence already picked up, which answers all your above questions except for… tags. Far spread and a good practice are tag names with relation to the version, and from those the most common is `v<versionName>`. Alternatively, you also could base it on something like `c<versionCode>` (the leading character just making sure its a string; it's optional). Most important is: once decided for a pattern, please stick to it :wink:

**Comment by Helium314** [comment]
Not helping at all, but I'm really happy to see this getting (almost) done!

**Comment by Slion** [comment]
Yes, it looks like all I need is create a label and they would happily publish it. Ideally I would like to automate the whole fdroid release process using something [like that](https://www.geeksforgeeks.org/automated-release-for-android-using-github-actions/). Let's see how it goes.

**Comment by IzzySoft** [comment]
I've read quite often that devs implemented "Github actions" for that, so it seems a good approach.

**Comment by Slion** [comment]
I just published v1.8.8 on Slions.net, it's also in the process of being published on Google Play and I tagged it and notified the guys at [fdroid](https://gitlab.com/fdroid/rfp/-/issues/1442#note_1033442035).

**Comment by Slion** [comment]
Apparently it takes up to 5 days for the app to show up in F-Droid. I'll close this issue once we have confirmed sighting of Fulguris in F-Droid.

**Comment by IzzySoft** [comment]
Watch the toots of [@IzzyOnDroid@Mastodon.technology](https://mastodon.technology/@IzzyOnDroid) – especially those carrying the [`#AndroidAppRain`](https://mastodon.technology/tags/AndroidAppRain) hash tag, and you'll be notified of new apps appearing at F-Droid :smiley:

**Comment by Slion** [comment]
Good job team:
https://f-droid.org/packages/net.slions.fulguris.full.fdroid/

**Comment by Slion** [comment]
The license shown is not complete. It shows only MPL-2.0 it should also show CPAL-1.0. Not sure where I can fix this. Can I edit the [metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/net.slions.fulguris.full.fdroid.yml) or those generated somehow.

**Comment by IzzySoft** [comment]
You will have to choose. Metadata (at least currently) support only a single license. And no, a comma-separated list does not wok – that would lead to the app being rejected as the string is compared to "accepted licenses" directly. So if you want to have CPAL instead of MPL, that's possible; just open a corresponding merge request at fdroiddata.
