### ISSUE TITLE
Add quick way to exit Incognito mode

### ISSUE THREAD

**Issue by jamal2362** [Slion/Fulguris#93]
There is no way to leave the incognito mode.

Workaround is to close all incognito tabs to get into normal mode.

![Screenshot_20201124-102907](https://user-images.githubusercontent.com/15986930/100075171-e7b2bc80-2e3f-11eb-9a3c-00da65080b46.jpg)

**Comment by Slion** [comment]
Did you try Ctrl+Q?
There should indeed be a menu option to exit incognito mode.

**Comment by jamal2362** [comment]
Hey,
My Phone doesn't exist a Keyboard.
Yes a Button top leave the incognito Mode ist very useful :)

**Comment by Slion** [comment]
You can also just close the app from the task list you know.
