### ISSUE TITLE
Add option to open downloaded files

### ISSUE THREAD

**Issue by jamal2362** [Slion/Fulguris#94]
Downloaded .apk files cannot be opened after download, so there is no message for the package installer.
Only the File Explorer opens.

**Comment by Slion** [comment]
Yes that's by design for now. We do not open downloaded files we just show them in your file explorer. Ideally there should be a settings option or a dialog to choose what you want to do with downloaded files: open it or show it in file explorer.

**Comment by Slion** [comment]
That's a duplicate of #156
