### ISSUE TITLE
Video call not working

### ISSUE THREAD

**Issue by Slion** [Slion/Fulguris#96]
Device: FxTec Pro1
OS: Android 9

You can try video call on that web site:
https://app.arztkonsultation.de

When WebRTC is enabled from privacy settings you get the dialogs asking for permissions but the web site still fails to access microphone and camera.
Without WebRTC it still fails and you don't even get the dialogs. 

Fix should be easy:
1. Set mediaPlaybackRequiresUserGesture to false.
2. We should also prompt user to enable Camera and Microphone permissions.

Test it from:
https://webrtc.github.io/samples/
https://apprtc-m.appspot.com/
https://test.webrtc.org
https://appr.tc/

See:
https://github.com/googlearchive/chromium-webview-samples/tree/master/webrtc-example
https://stackoverflow.com/questions/37848110/no-audio-in-webrtc-over-webview-in-android-app
https://stackoverflow.com/a/64660386/3969362

**Comment by jamal2362** [comment]
Can confirm that bug!

**Comment by jamal2362** [comment]
Hi,
I installed your 1.3.9 and WebRTC is still broken. I have given the page permission but unfortunately no success.

![Screenshot_20210209-230804](https://user-images.githubusercontent.com/15986930/107435156-103b8000-6b2c-11eb-8a56-fadcaf458791.jpg)

**Comment by Slion** [comment]
@jamal2362 You need to got to system settings and give the app Camera and Microphone permissions. See #154.
Thanks for testing.

**Comment by jamal2362** [comment]
Thanks that's it. I thought I had already given the microphone and camera permissions. 😄
No Problem ☺️
